/* Short, offline-first teaching cards for the 45 roadmap topics. Each card has
 * one concept, a worked application and two questions with explained answers. */
window.STUDY_LESSONS = {
  quant: {
    arithmetic: ['Place value and the four operations','Add/subtract by place value; multiply as repeated groups; divide into equal groups. Estimate first so a misplaced digit stands out.','248 + 176 = (200+100)+(40+70)+(8+6) = 424.', [['36 × 5','180','30 × 5 + 6 × 5 = 150 + 30.'],['144 ÷ 12','12','12 groups of 12 make 144.']]],
    bodmas: ['Order of operations','Do brackets first, then powers, division and multiplication left to right, then addition and subtraction left to right. Division does not always precede multiplication.','18 ÷ 3 × 2 + 4 = 6 × 2 + 4 = 16.', [['8 + 6 ÷ 2','11','Divide before adding: 8 + 3.'],['(8+6) ÷ 2','7','The brackets make 14 before division.']]],
    fractions: ['Parts of a whole','A fraction a/b means a parts when a whole is split into b equal parts. To add, convert to a common denominator; to multiply, multiply numerators and denominators.','1/3 + 1/6 = 2/6 + 1/6 = 1/2.', [['3/4 of 20','15','20 ÷ 4 × 3.'],['2/3 × 3/5','2/5','Multiply and cancel 3.']]],
    decimals: ['Place values after the point','Tenths, hundredths and thousandths are fractions with denominators 10, 100 and 1000. Line up decimal points for addition; count decimal places after multiplication.','1.2 × 0.3: 12 × 3 = 36 with two decimal places, so 0.36.', [['0.75 + 1.2','1.95','Write 1.20 and add by place value.'],['2.5 × 4','10','25 tenths × 4 = 100 tenths.']]],
    'lcm-hcf': ['Smallest common multiple, largest common factor','HCF uses common prime factors with smaller powers; LCM uses every prime factor with larger powers. For two positive integers, HCF × LCM equals their product.','12 = 2²×3, 18 = 2×3². HCF = 2×3 = 6; LCM = 2²×3² = 36.', [['HCF of 15 and 25','5','Both share factor 5 only.'],['LCM of 4 and 6','12','12 is the first multiple of both.']]],
    divisibility: ['Fast divisibility checks','A number is divisible by 2 if its last digit is even, by 3 if its digit sum is divisible by 3, by 5 if it ends in 0 or 5, and by 9 if its digit sum is divisible by 9.','For 234, digit sum 2+3+4=9: divisible by 3 and 9. Last digit 4: also by 2.',''.split()],
    'squares-cubes': ['Know a few anchor powers','A square is n×n; a cube is n×n×n. Use nearby anchors instead of memorising a huge table. (a+b)² = a²+2ab+b².','21² = (20+1)² = 400+40+1 = 441.', [['12²','144','(10+2)² = 100+40+4.'],['5³','125','5×5×5.']]],
    percentage: ['Percent means per hundred','x% = x/100. A percent change compares the change with the ORIGINAL value. Successive changes multiply, rather than add, their factors.','20% of 250 = 0.2×250 = 50. Raising 250 by 20% gives 300.', [['15% of 200','30','10% is 20 and 5% is 10.'],['From 80 to 100: increase %','25%','Change 20 divided by original 80.']]],
    ratio: ['Compare quantities in equal units','A:B = 2:3 means A=2 parts, B=3 parts. For a total, add the ratio parts first, then split. Convert units before comparing.','₹250 split 2:3 has 5 parts of ₹50, giving ₹100 and ₹150.', [['Split 70 in ratio 3:4: first share','30','Each of 7 parts is 10.'],['2:5 = x:20; x?','8','Multiply both terms by 4.']]],
    average: ['Total divided by count','Average = sum/count. If you know average and count, total = average×count. Do not average averages from groups of unequal sizes without weighting.','Five scores averaging 12 total 60. Add 18: new average = 78/6 = 13.', [['Average of 4, 6, 8','6','Sum 18 divided by 3.'],['4 items average 10: total','40','Average × count.']]],
    'profit-loss': ['Compare selling price with cost price','Profit = selling price − cost price. Profit % uses cost price as denominator; discount % uses marked price. Keep their bases separate.','Cost ₹200, marked ₹300, discount 10%: sell ₹270; profit ₹70 or 35% of cost.', [['Cost 100, sell 120: profit %','20%','20/100 × 100.'],['Marked 500, 20% off: price','400','Subtract 100 from 500.']]],
    'simple-interest': ['Interest only on principal','Simple interest SI = P×R×T/100 when R is annual percent and T is years. Amount = P+SI. Convert months to years.','₹1,000 at 6% for 2 years: SI = 1000×6×2/100 = ₹120.', [['₹500 at 10% for 2 years: SI','₹100','500×10×2/100.'],['₹1000 at 12% for 6 months: SI','₹60','T is half a year.']]],
    'compound-interest': ['Interest earns interest','Annual amount A=P(1+r/100)^n. Compound interest = A−P. A different compounding frequency changes the period rate and count.','₹1,000 at 10% for 2 years becomes 1000×1.1² = ₹1,210; CI ₹210.', [['₹100 at 10% for 2 years: amount','₹121','100×1.1×1.1.'],['₹500 at 20% for 1 year: CI','₹100','One year is 20% of 500.']]],
    'time-work': ['Use work rates, not days directly','If A finishes a job in a days, A does 1/a of it per day. Add independent workers’ rates; time = 1/combined rate.','A takes 6 days, B takes 3. Together rate = 1/6+1/3=1/2 job/day; time 2 days.', [['A takes 4, B takes 4: together','2 days','Two rates of 1/4 add to 1/2.'],['Rate 1/5 job/day: time','5 days','One job divided by one-fifth.']]],
    pipes: ['Filling positive, draining negative','Treat inlet rates as positive fractions of a tank per hour and outlet rates as negative. Add rates before taking the reciprocal.','Inlet fills in 4h, outlet empties in 8h: net 1/4−1/8=1/8 tank/h, so 8h.', [['Fill 6h, empty 12h: net time','12 hours','1/6−1/12=1/12.'],['Two 4h inlets: time','2 hours','Combined rate is 1/2 per hour.']]],
    'speed-distance': ['Connect speed, distance and time','Distance = speed×time. Keep units consistent: km/h to m/s multiplies by 5/18. Relative speed adds for opposite directions and subtracts for same direction.','60 km/h for 2.5h covers 150 km.', [['90 km/h in m/s','25 m/s','90×5/18.'],['40 km at 20 km/h: time','2 hours','40/20.']]],
    trains: ['Train crossing is distance over relative speed','Crossing a pole covers the train’s own length; crossing a platform covers train length + platform length. Crossing another train uses the sum of their lengths and relative speed.','A 120m train at 12m/s passes a pole in 120/12 = 10 seconds.', [['120m train, 80m platform, 20m/s: time','10 seconds','Travel 200m at 20m/s.'],['Train 150m at 15m/s past a pole','10 seconds','150/15.']]],
    boats: ['Current changes effective speed','Downstream speed = still-water boat speed + stream speed; upstream = boat speed − stream speed. Half their difference gives stream speed.','Downstream 12 km/h, upstream 8 km/h: boat 10, stream 2 km/h.', [['Boat 15, stream 3: upstream','12 km/h','Subtract stream speed.'],['Downstream 18, upstream 10: stream','4 km/h','(18−10)/2.']]],
    'number-system': ['Integers, remainders and factors','An integer is even or odd; primes have exactly two positive factors. Division algorithm: number = divisor×quotient + remainder, with 0 ≤ remainder < divisor.','29 ÷ 5 gives quotient 5 and remainder 4: 29=5×5+4.', [['Remainder of 38 ÷ 6','2','6×6=36.'],['Is 1 prime?','No','A prime must have exactly two positive divisors.']]],
    mixture: ['Weighted averages and alligation','A mixture’s concentration is total ingredient divided by total mixture. For two concentrations a and b around target m, quantities are in ratio (b−m):(m−a).','Mix 20% and 50% to get 30%: amounts 20%:50% = (50−30):(30−20)=2:1.', [['Equal litres of 10% and 30%: result','20%','Equal-weight average.'],['2 L pure water + 2 L 50% juice: concentration','25%','1 L juice in 4 L total.']]],
    partnership: ['Profit follows capital × time','In ordinary partnership questions, divide profit in the ratio of each person’s invested capital multiplied by how long it was invested.','A invests ₹1000 for 12 months, B ₹2000 for 6: both contribute 12000 capital-months, so split equally.', [['A 1000×12, B 1000×6: ratio','2:1','Compare capital-months.'],['₹300 profit in 2:1 ratio: larger share','₹200','Three shares of ₹100.']]],
    ages: ['Translate time into equations','Every person ages by the same number of years, so the age difference stays fixed. Write present ages as variables; apply “ago” or “after” to each person.','A is twice B now and their sum is 36: B=x, A=2x, so 3x=36 and A=24.', [['A 20, B 12: difference in 5 years','8','Both ages rise by 5.'],['Twice an age is 30: age','15','Solve 2x=30.']]],
    di: ['Read the chart before calculating','Check title, units, scale, period and denominator. For percent change use (new−old)/old × 100; for a share use part/total × 100.','Sales rise from 40 to 50 lakh: change 10/40×100=25%, not 20%.', [['A=30, B=20: total','50','Add both categories.'],['A=30 of total 50: share','60%','30/50×100.']]],
    algebra: ['Keep equations balanced','A variable stands for an unknown. Apply the same operation to both sides; combine like terms. (a+b)² = a²+2ab+b² and (a+b)(a−b)=a²−b².','3x+5=20: subtract 5, divide 3, x=5.', [['2x−4=10: x','7','2x=14.'],['(x+2)(x−2)','x²−4','Difference of squares.']]],
    geometry: ['Angles and triangle rules','Straight-line angles sum to 180°, around a point to 360°, and angles inside a triangle to 180°. A right triangle obeys a²+b²=c².','Triangle has angles 50° and 60°: third is 180−110=70°.', [['Right triangle legs 3 and 4: hypotenuse','5','√(9+16)=5.'],['Supplement of 110°','70°','Straight line sums to 180°.']]],
    mensuration: ['Area is square units, volume cubic units','Rectangle area = length×width, perimeter = 2(length+width). Circle area = πr², circumference = 2πr. Cuboid volume = l×w×h.','Rectangle 5cm by 4cm: area 20cm², perimeter 18cm.', [['Square side 6: area','36 square units','Side × side.'],['Cuboid 2×3×4: volume','24 cubic units','Multiply all three dimensions.']]],
    trigonometry: ['Right-triangle side ratios','Relative to an acute angle θ: sinθ=opposite/hypotenuse, cosθ=adjacent/hypotenuse, tanθ=opposite/adjacent. sin²θ+cos²θ=1.','In a 3-4-5 triangle, opposite=3 and adjacent=4: sinθ=3/5, tanθ=3/4.', [['If opposite=4, hypotenuse=5: sinθ','4/5','Opposite divided by hypotenuse.'],['tan 45°','1','Equal opposite and adjacent legs.']]]
  },
  reasoning: {
    analogy: ['Find the shared relationship','Do not match words by surface appearance. State how the first pair connects, then apply the same rule to the second. Check direction.','Bird : nest :: bee : hive. Both pairs connect an animal to its home.', [['Hand : glove :: foot : ?','shoe','An item worn on that body part.'],['2 : 4 :: 3 : ?','9','Second number is the square of first.']]],
    classification: ['Choose the one that breaks the rule','Find a property shared by most items: category, parity, spelling pattern or shape. Test whether the odd item breaks that exact rule.','2, 4, 6, 9: 9 is odd while the other three are even.', [['Apple, mango, carrot, banana','carrot','It is a vegetable; others are fruits.'],['3, 5, 7, 9','9','It is composite; others are prime.']]],
    series: ['Look for successive differences','Check +/− gaps, multiplication, alternating subsequences, squares and letters’ positions. Verify the rule across the whole series, not just one step.','2, 5, 10, 17: gaps 3, 5, 7, so next gap 9 gives 26.', [['3, 6, 12, 24, ?','48','Double each term.'],['A, C, F, J, ?','O','Letter positions jump 2, 3, 4, then 5.']]],
    coding: ['Infer and apply one consistent rule','Compare matching letters and positions: forward/backward shifts, reversals, substitutions or number positions. Confirm every character before coding the new word.','If CAT → DBU, each letter shifts forward one: DOG → EPH.', [['If BAT → CBU, code CAT','DBU','Shift each letter forward one.'],['If ABC → CBA, code DOG','GOD','Reverse letter order.']]],
    alphabet: ['Use letter positions','A=1 through Z=26. For letters from the right, position = 27−position from left. Fix the direction before counting to avoid off-by-one errors.','E is 5th from left and 22nd from right: 27−5=22.', [['10th letter','J','Count A as 1.'],['Position of X from right','3','Z=1, Y=2, X=3.']]],
    'blood-relations': ['Draw a small family tree','Translate each statement into parent, child, sibling or spouse arrows. Do not assume gender unless given. Build from the named person outward.','A is B’s mother; B is C’s brother. A is also C’s mother.', [['Your mother’s brother','maternal uncle','He is your mother’s sibling.'],['Father’s father','paternal grandfather','Parent of your father.']]],
    directions: ['Use a coordinate sketch','Set north as +y, east as +x; west and south are negative. Track turns from the CURRENT facing direction. Net distance may differ from distance walked.','Walk 3 east then 4 north: straight-line distance from start is 5 by 3-4-5 triangle.', [['3 north, 3 south: displacement','0','You return to the start.'],['Facing north, turn right','east','Clockwise quarter-turn from north.']]],
    ranking: ['Count endpoints once','If a person ranks L from left and R from right, total = L+R−1. For two people with positions, sketch the line before counting between them.','7th from left and 9th from right: total 7+9−1=15.', [['4th from left, 6th from right: total','9','4+6−1.'],['5th and 9th from left: between','3','Positions 6, 7, 8.']]],
    syllogism: ['Conclusions must follow, not merely seem plausible','Treat “all”, “some” and “no” as set relationships. A conclusion is valid only if it holds in every arrangement allowed by the premises; never invent a converse.','All cats are mammals. All mammals are animals. Therefore all cats are animals.', [['All A are B. All B are C. All A are C?','Yes','Containment carries through.'],['All A are B. Are all B A?','Not necessarily','B may include other things.']]],
    venn: ['Overlap sets accurately','A circle represents a set. The overlap belongs to both. In counts, |A∪B|=|A|+|B|−|A∩B|; subtract overlap once to avoid double counting.','20 like tea, 15 coffee, 5 both: 20+15−5=30 like at least one.', [['10 A, 8 B, 3 both: either','15','10+8−3.'],['All cats are animals: placement','cat circle inside animal circle','Every cat is an animal.']]],
    seating: ['Fix a frame and place definite clues first','Write a row or circle with facing direction marked. Facing south reverses left/right from your view. Put direct neighbours and endpoints first; test remaining cases.','Three seats left to right: A sits left of B, C sits right of B. Order A-B-C.', [['A-B-C left to right: who is between?','B','B has a neighbour on each side.'],['Facing north: left-hand direction','west','North-facing left points west.']]],
    puzzles: ['Turn clues into a table','List people, places and attributes in rows/columns. Mark impossible pairings first. Use every clue and check the finished table against all constraints.','A and B choose tea/coffee. A does not take tea. So A takes coffee; B takes tea.', [['A/B use red/blue; B is blue. A?','red','Each colour used once.'],['Three days M/T/W; A not M or W. A?','Tuesday','Only Tuesday remains.']]],
    statement: ['Separate given facts from outside knowledge','For a statement-conclusion item, accept only what necessarily follows from the given words. “Some” does not imply “all”; a possibility is not a certainty.','Statement: All buses are vehicles. Conclusion: Some vehicles are buses. If buses exist, that follows; all vehicles being buses does not.', [['All squares are rectangles. All rectangles squares?','No','Rectangles may have unequal sides.'],['No A are B. Can an A be B?','No','The sets are disjoint.']]],
    operations: ['Substitute the defined symbols first','If a question redefines +, −, × or ÷, rewrite each symbol as its stated operation, then use normal BODMAS. Do not apply the familiar symbol’s meaning by habit.','If @ means +, then 4 @ 5 × 2 = 4 + 10 = 14.', [['If # means multiplication: 3 # 4','12','Replace # with ×.'],['If @ means subtraction: 8 @ 3 + 1','6','8−3+1, left to right.']]],
    figures: ['Describe a visual rule before guessing','For a figure sequence, count sides, shaded regions and rotations. Track one change at a time; test each candidate against ALL elements of the figure.','An arrow pointing up, right, down rotates 90° clockwise each step; next points left.', [['Triangle, square, pentagon: next sides','6','Side count increases by one.'],['↑, →, ↓, ?','←','Rotate 90° clockwise.']]],
    mirror: ['Reflect across the correct axis','A mirror on the right reverses left and right, not top and bottom; water reflection reverses top and bottom. For a clock mirror, draw the hand positions rather than swapping numbers blindly.','A dot in the upper-left corner moves to upper-right in a vertical mirror, but to lower-left in water.', [['Vertical mirror of left-positioned dot','right-positioned dot','Horizontal position flips.'],['Water reflection of top dot','bottom dot','Vertical position flips.']]],
    paper: ['Unfold in reverse order','Each fold duplicates a cut across its crease on unfolding. Sketch the crease and mark which layers the punch crosses. A cut on the crease may produce fewer distinct holes.','Fold a sheet once in half and punch away from the fold: opening it gives two mirrored holes.', [['One fold, one off-crease punch: holes','2','Punch passes two layers.'],['Two half-folds, off-crease punch: holes','4','Four layers are pierced.']]],
    spatial: ['Break the shape into stable features','For embedded figures, ignore overall size and rotation but preserve connections and line intersections. For cube views, opposite faces never appear adjacent in the same view.','A small triangle made by three connected line segments remains embedded even if extra crossing lines surround it.', [['Can opposite cube faces share an edge?','No','They lie on opposing planes.'],['Rotation changes number of vertices?','No','Only orientation changes.']]]
  }
};
// Complete the divisibility card with the same two-question contract.
window.STUDY_LESSONS.quant.divisibility[3] = [['Is 135 divisible by 9?','Yes','Digits sum to 9.'],['Is 142 divisible by 5?','No','It ends in 2, not 0 or 5.']];
