/* ============================================================================
   CURRICULUM — teaches from zero, in dependency order.
   ----------------------------------------------------------------------------
   Each lesson is: read it, then prove it. A topic does not unlock the next one
   until you pass its check, so you cannot arrive at page-replacement algorithms
   without knowing what a page is.

   Order is deliberate. Big-O comes first because every later complexity claim
   is meaningless without it. Processes come before scheduling. Keys come before
   normalisation.

   Coverage: all ten examined subjects, 42 lessons. Depth follows weight — the
   P1 technical subjects carry the bulk of the 100 technical marks and get the
   most lessons; Software Engineering is two, because that is honestly all it is
   worth in this paper.

   Block types:
     h  heading          p  paragraph
     l  bullet list      c  code / worked example
     k  key point (the thing to remember)
   ========================================================================== */

const CURRICULUM = [

/* ─────────────────────────── DATA STRUCTURES ─────────────────────────── */
{
  key: "ds-bigo", subject: "Data Structures", topic: "Data Structures",
  title: "Reading Big-O", minutes: 7,
  video: {url:"https://www.youtube.com/watch?v=P5338HzZX7E",
          title:"Big O Notation | Asymptotic Notation | GATECSE | DAA", channel:"THE GATEHUB"},
  why: "Every later claim — 'a BST search is O(log n)' — is noise until you can read this notation. Start here.",
  blocks: [
    {h: "What it actually measures"},
    {p: "Big-O describes how the work grows as the input grows. It is not a stopwatch. O(n) does not mean 'n seconds' — it means doubling the input roughly doubles the work."},
    {p: "Constants and smaller terms are dropped, because they stop mattering as n gets large. 3n² + 500n + 9000 is O(n²): at n = 1,000,000 the n² term dwarfs everything else."},
    {h: "The ladder — memorise this once"},
    {c: "O(1) < O(log n) < O(√n) < O(n) < O(n log n) < O(n²) < O(2ⁿ) < O(n!)"},
    {l: [
      "O(1) — constant. Array index, hash lookup. Input size is irrelevant.",
      "O(log n) — halving each step. Binary search, balanced tree search.",
      "O(n) — touch everything once. A single loop over the data.",
      "O(n log n) — the best a comparison sort can do. Merge sort, heap sort.",
      "O(n²) — nested loop over the same data. Bubble, selection, insertion sort.",
    ]},
    {h: "How to spot it in code"},
    {p: "Count the nesting over the input. One loop over n items is O(n). A loop inside a loop, both over n, is O(n²). A loop that halves the range each pass is O(log n)."},
    {c: "for (i = 0; i < n; i++)          // O(n)\n  for (j = 0; j < n; j++)        // O(n) inside O(n)\n    sum += a[i] * a[j];          // → O(n²)\n\nwhile (n > 1) n = n / 2;         // O(log n) — halving"},
    {h: "Worst, average, best"},
    {p: "Exams almost always mean WORST case unless they say otherwise. QuickSort is O(n log n) on average but O(n²) at worst — and the worst case is the answer they want."},
    {k: "Halving → log. One pass → n. Nested passes → n². Anything that both splits and passes → n log n."},
  ],
},
{
  key: "ds-array-list", subject: "Data Structures", topic: "Data Structures",
  title: "Arrays and Linked Lists", minutes: 7,
  why: "The first real trade-off in the subject: instant access versus cheap insertion. Nearly every structure after this is built on one of them.",
  blocks: [
    {h: "Array — contiguous memory"},
    {p: "All elements sit next to each other, so the address of element i is base + i × size. One arithmetic step, no walking. That is why array access is O(1)."},
    {p: "The cost is insertion. To insert at the front, every other element must shift right — O(n). And the size is fixed at allocation."},
    {h: "Linked list — nodes and pointers"},
    {p: "Each node holds a value and the address of the next node. Nodes can be anywhere in memory, so growing costs nothing and inserting at the head is two pointer writes — O(1)."},
    {p: "The cost is access. There is no arithmetic shortcut to the 5th node; you must start at the head and follow 5 pointers — O(n)."},
    {h: "The trade-off in one table"},
    {c: "                 Array      Linked list\naccess i-th      O(1)       O(n)\ninsert at head   O(n)       O(1)\ninsert at tail   O(1)*      O(n) without a tail pointer\nsearch           O(n)       O(n)\nmemory           compact    extra pointer per node"},
    {p: "* amortised, if there is spare capacity."},
    {h: "Singly vs doubly"},
    {p: "A singly linked node knows only its successor. To delete a node you need its predecessor, so you walk from the head — O(n). A doubly linked node knows both neighbours, so deletion given a pointer is O(1)."},
    {k: "Array = address arithmetic = instant read, expensive insert. Linked list = pointer chasing = cheap insert, slow read."},
  ],
},
{
  key: "ds-stack-queue", subject: "Data Structures", topic: "Data Structures",
  title: "Stacks and Queues", minutes: 6,
  why: "Two structures with one rule each, and both turn up constantly — recursion, BFS, DFS, expression evaluation.",
  blocks: [
    {h: "Stack — LIFO"},
    {p: "Last in, first out. Push adds to the top, pop removes from the top. Both O(1). Think of a stack of plates: you can only take the one you put down last."},
    {l: [
      "Function calls — each call pushes an activation record, returns pop it. That is why recursion 'uses a stack'.",
      "Undo — the last action is the first undone.",
      "Postfix evaluation — push operands, and on an operator pop the last two.",
      "DFS — go as deep as possible, back up when stuck.",
    ]},
    {h: "Queue — FIFO"},
    {p: "First in, first out. Enqueue at the rear, dequeue from the front. Like a ticket counter: whoever arrived first is served first."},
    {l: [
      "BFS — explore all neighbours at one distance before going deeper.",
      "Scheduling — processes waiting for the CPU in arrival order.",
      "Buffers — printer jobs, keyboard input.",
    ]},
    {h: "The circular queue"},
    {p: "In a plain array queue, repeated dequeues leave dead space at the front that can never be reused, even when the queue is empty. Wrapping the rear pointer round to index 0 reclaims it."},
    {k: "BFS = Breadth = Queue. DFS = Depth = Stack. B-Q, D-S."},
  ],
},
{
  key: "ds-trees", subject: "Data Structures", topic: "Data Structures",
  title: "Trees and Binary Search Trees", minutes: 8,
  why: "The BST is where O(log n) first appears in a data structure, and traversal order is asked in almost every paper.",
  blocks: [
    {h: "Vocabulary first"},
    {l: [
      "Root — the single top node. Leaf — a node with no children.",
      "Height — the longest path from root to a leaf, counted in edges.",
      "A tree with n nodes has exactly n − 1 edges: every node but the root has one parent.",
      "Binary tree — each node has at most two children.",
    ]},
    {h: "The BST rule"},
    {p: "For every node: everything in the left subtree is smaller, everything in the right subtree is larger. That single rule is what makes search fast."},
    {p: "Searching, you compare once and discard an entire subtree. On a balanced tree of n nodes the height is log₂n, so search is O(log n)."},
    {h: "The catch"},
    {p: "Insert 1, 2, 3, 4, 5 into an empty BST in that order and every node becomes a right child. The tree is a linked list with extra steps, and search degrades to O(n). This is why AVL and red-black trees exist — they rebalance on insert."},
    {h: "Traversals"},
    {c: "Inorder    Left, Node, Right   → sorted order for a BST\nPreorder   Node, Left, Right   → copying / serialising a tree\nPostorder  Left, Right, Node   → deleting / freeing a tree\nLevel      row by row          → uses a QUEUE, not recursion"},
    {p: "The prefix tells you where the root is visited: PRE = first, IN = middle, POST = last."},
    {k: "IN-order gives INcreasing order. Postorder frees a tree safely — children die before their parent."},
  ],
},
{
  key: "ds-heap", subject: "Data Structures", topic: "Data Structures",
  title: "Heaps and Priority Queues", minutes: 6,
  why: "A heap looks like a tree and lives in an array. It is the answer to 'give me the largest thing, repeatedly'.",
  blocks: [
    {h: "The heap property"},
    {p: "In a max-heap every parent is ≥ its children. Apply that all the way up and the maximum must be at the root. A min-heap is the same rule inverted."},
    {p: "Note what it does NOT say: siblings are unordered, and a heap is not sorted. Only the root is guaranteed."},
    {h: "It is stored in an array"},
    {p: "A heap is a complete binary tree — every level full except possibly the last, filled left to right — so it maps onto an array with no gaps and no pointers."},
    {c: "for node at index i (0-based):\n  left child  = 2i + 1\n  right child = 2i + 2\n  parent      = (i − 1) / 2"},
    {h: "Costs"},
    {l: [
      "Find max — O(1). It is at index 0.",
      "Insert — put it at the end, then bubble up while it beats its parent. Bounded by the height: O(log n).",
      "Delete max — move the last element to the root, sift it down. O(log n).",
      "BUILD a heap from an unsorted array — O(n), not O(n log n). Most nodes are near the bottom and barely move.",
    ]},
    {k: "Build a heap = O(n). Heap SORT = O(n log n) — n deletions at log n each. Exams bank on you conflating the two."},
  ],
},
{
  key: "ds-graphs", subject: "Data Structures", topic: "Data Structures",
  title: "Graphs, BFS and DFS", minutes: 7,
  why: "Trees are a special case of graphs. Once you can traverse a graph, shortest paths and connectivity follow.",
  blocks: [
    {h: "Representation"},
    {p: "Adjacency matrix — a V × V grid, with a cell for every possible pair whether or not the edge exists. O(V²) space, O(1) edge lookup."},
    {p: "Adjacency list — for each vertex, a list of its actual neighbours. O(V + E) space. For sparse graphs, which is most real graphs, this is far better."},
    {h: "BFS — breadth first"},
    {p: "Visit all neighbours at distance 1, then distance 2, and so on. Uses a QUEUE. Because it expands in rings, the first time it reaches a node it has found the shortest path in edges — which is why BFS gives shortest paths on unweighted graphs."},
    {h: "DFS — depth first"},
    {p: "Go as deep as possible down one path, then back up and try the next. Uses a STACK, usually the call stack via recursion. Used for cycle detection, topological sort and connected components."},
    {c: "Both visit every vertex and edge once:\n  adjacency list   → O(V + E)\n  adjacency matrix → O(V²)   (you must scan a whole row per vertex)"},
    {k: "BFS = rings = queue = shortest path. DFS = tunnel = stack = cycles and ordering."},
  ],
},
{
  key: "ds-sorting", subject: "Data Structures", topic: "Data Structures",
  title: "Sorting — the comparison table", minutes: 7,
  why: "Sorting questions are nearly free marks, because they are almost always 'which one has this property'.",
  blocks: [
    {h: "The table to know cold"},
    {c: "            best        average     worst       stable  in-place\nBubble      O(n)        O(n²)       O(n²)       yes     yes\nSelection   O(n²)       O(n²)       O(n²)       no      yes\nInsertion   O(n)        O(n²)       O(n²)       yes     yes\nMerge       O(n log n)  O(n log n)  O(n log n)  yes     NO\nQuick       O(n log n)  O(n log n)  O(n²)       no      yes\nHeap        O(n log n)  O(n log n)  O(n log n)  no      yes"},
    {h: "Why QuickSort's worst case is O(n²)"},
    {p: "It picks a pivot and partitions around it. If the pivot is always the smallest or largest element, one side holds n − 1 items and the other holds none — so it recurses n deep doing O(n) work each time. An already-sorted array with a first-element pivot triggers exactly this."},
    {h: "Why MergeSort never has a bad day"},
    {p: "It splits at the midpoint regardless of the data — log n levels — and merges each level in O(n). The input cannot influence the split. The price is O(n) extra memory, so it is not in-place."},
    {h: "Stability"},
    {p: "A stable sort keeps equal elements in their original relative order. It matters when you sort by one key after another — sort by name, then by department, and a stable sort leaves each department alphabetical."},
    {k: "Stable: Merge, Insertion, Bubble, Counting. Not stable: Quick, Heap, Selection."},
  ],
},

/* ────────────────────────── OPERATING SYSTEMS ────────────────────────── */
{
  key: "os-process", subject: "Operating Systems", topic: "Operating Systems",
  title: "Processes and the PCB", minutes: 6,
  why: "Everything else in OS — scheduling, deadlock, memory — is about managing these. Start with what one is.",
  blocks: [
    {h: "Program vs process"},
    {p: "A program is a file on disk — passive. A process is a program in execution — active, with its own memory, registers and program counter. Run the same program twice and you have two processes."},
    {h: "The Process Control Block"},
    {p: "The OS keeps one PCB per process, holding its id, state, program counter, registers, memory pointers and open files. A context switch is: save the running process's state into its PCB, load the next process's PCB. Memory is not copied — the page tables just switch."},
    {p: "A context switch does no user work. It is pure overhead, which is why an extremely small scheduling quantum makes a system slower, not more responsive."},
    {h: "The five states"},
    {c: "new → ready ⇄ running → terminated\n              ↓   ↑\n           waiting (blocked on I/O)"},
    {p: "Only one process per CPU core is running at any instant. Ready means 'able to run, waiting for the CPU'. Waiting means 'cannot run until I/O completes' — a waiting process is not competing for the CPU at all."},
    {h: "Process vs thread"},
    {p: "Threads within a process share memory and open files; each has its own stack and registers. That makes switching between threads cheaper than between processes, and it is also why threads need synchronisation and separate processes usually do not."},
    {k: "Zombie = finished but the parent has not read its exit status. Orphan = still running, parent died, adopted by init."},
  ],
},
{
  key: "os-sched", subject: "Operating Systems", topic: "Operating Systems",
  title: "CPU Scheduling", minutes: 8,
  video: {url:"https://www.youtube.com/watch?v=zFnrUVqtiOY",
          title:"L-2.1: Process Scheduling Algorithms (Preemption vs Non-Preemption)", channel:"Gate Smashers"},
  why: "The most reliably examined OS topic, and the numericals are mechanical once you can draw a Gantt chart.",
  blocks: [
    {h: "The three numbers"},
    {c: "Completion time (CT) — when the process finishes\nTurnaround (TAT)      = CT − arrival time\nWaiting time (WT)     = TAT − burst time"},
    {p: "Draw the Gantt chart first, read completion times off it, then apply those two subtractions. Almost every scheduling numerical is that and nothing more."},
    {h: "The algorithms"},
    {l: [
      "FCFS — first come, first served. Non-preemptive. Simple, and suffers the convoy effect: one long process at the head delays everyone behind it.",
      "SJF — shortest job first. Provably optimal for average waiting time, but needs burst lengths in advance, which you do not have. Starves long jobs.",
      "SRTF — preemptive SJF. A shorter arrival preempts the running process.",
      "Round Robin — each process gets one quantum, then goes to the back of the queue. Preemptive, fair, nobody starves.",
      "Priority — highest priority first. Without aging, low-priority processes can starve forever.",
    ]},
    {h: "Round Robin's quantum"},
    {p: "Too large and no process is ever preempted, so it degenerates into FCFS. Too small and the system spends its time context switching instead of executing. The quantum should comfortably exceed a context switch but stay under a typical burst."},
    {h: "Starvation and its cure"},
    {p: "Starvation is indefinite postponement. Aging fixes it: raise a process's priority the longer it has waited, so anything waiting long enough eventually runs. FCFS and Round Robin cannot starve anyone by construction."},
    {k: "Optimal average waiting time = SJF. Convoy effect = FCFS. Starvation = priority without aging. Huge quantum = FCFS again."},
  ],
},
{
  key: "os-deadlock", subject: "Operating Systems", topic: "Operating Systems",
  title: "Deadlock", minutes: 7,
  video: {url:"https://www.youtube.com/watch?v=A46BUTxcNfw",
          title:"Operating System Unit 3 One Shot — CPU Scheduling + Deadlock", channel:"Bitwise Learning"},
  why: "Four conditions, four strategies. Learn them as two lists and the questions answer themselves.",
  blocks: [
    {h: "The four necessary conditions"},
    {p: "All four must hold simultaneously. Break any one and deadlock is impossible."},
    {l: [
      "Mutual exclusion — a resource cannot be shared.",
      "Hold and wait — a process holds one resource while waiting for another.",
      "No preemption — a resource cannot be forcibly taken away.",
      "Circular wait — a cycle of processes each waiting on the next.",
    ]},
    {p: "The trap: the third is NO preemption. 'Preemption' on its own is not a deadlock condition — allowing it breaks deadlock."},
    {h: "The four strategies"},
    {l: [
      "Prevention — structurally deny one of the four conditions. E.g. force resources to be requested in a fixed global order, which makes a cycle impossible.",
      "Avoidance — allow the conditions, but refuse any request that would leave an unsafe state. This is Banker's algorithm.",
      "Detection — let it happen, find cycles in the wait-for graph, then recover by killing or rolling back a process.",
      "Ignore it — the ostrich algorithm. What general-purpose systems mostly do, because deadlock is rare and the cures are expensive.",
    ]},
    {h: "Banker's algorithm"},
    {p: "Each process declares its maximum need up front. On a request, the OS pretends to grant it and checks whether a safe sequence still exists — an order in which every process can finish with the resources left. If yes, grant; if no, make it wait. A safe state is never a deadlock; an unsafe state is not necessarily a deadlock, only a risk."},
    {k: "A banker checks before lending — that is AVOIDANCE, not prevention."},
  ],
},
{
  key: "os-memory", subject: "Operating Systems", topic: "Operating Systems",
  title: "Memory, Paging and Fragmentation", minutes: 8,
  why: "Paging is the single most examined memory topic, and the internal/external fragmentation split is a guaranteed mark.",
  blocks: [
    {h: "The problem"},
    {p: "Several processes must share physical memory without reading each other's data, and a process may be larger than the RAM available."},
    {h: "Paging"},
    {p: "Split logical memory into fixed-size pages and physical memory into frames of the same size. A page table maps each page to a frame. Because the size is fixed, any page fits any frame — so there are no unusable gaps between allocations."},
    {p: "What you do get is waste inside the last page: a process rarely fills it exactly. That is INTERNAL fragmentation."},
    {h: "Segmentation"},
    {p: "Split memory by logical unit instead — code, stack, heap — each a different size. That matches how a program is actually structured, but variable sizes leave odd gaps between allocations. That is EXTERNAL fragmentation: plenty of total free memory, no single hole big enough."},
    {h: "The TLB"},
    {p: "Every memory access would need an extra read of the page table, doubling access time. The TLB is a small associative cache of recent page-table entries, so most translations take no extra memory access at all."},
    {c: "effective access time = h × (TLB + mem) + (1 − h) × (TLB + mem + mem)\n  where h is the TLB hit ratio"},
    {h: "Virtual memory"},
    {p: "Only the pages in active use need to be resident. The rest live on disk and are fetched on demand. A page fault is not an error — it is the normal mechanism: the MMU traps, the OS loads the page, and the instruction restarts."},
    {k: "Fixed size → INternal waste (inside the last page). Variable size → EXternal gaps (between segments)."},
  ],
},
{
  key: "os-pagerepl", subject: "Operating Systems", topic: "Operating Systems",
  title: "Page Replacement and Thrashing", minutes: 6,
  why: "Belady's anomaly is asked almost every year, and the numericals are pure bookkeeping.",
  blocks: [
    {h: "The question"},
    {p: "Memory is full and a new page is needed. Which resident page gets evicted? Count the page faults over a reference string and you have the whole topic."},
    {h: "The algorithms"},
    {l: [
      "FIFO — evict the oldest resident page. Ignores whether it is still being used.",
      "LRU — evict the least recently used. A good approximation of the future, expensive to track exactly.",
      "Optimal (OPT/MIN) — evict the page needed furthest in the future. Unimplementable, since it requires knowing the future; used as a benchmark.",
      "LFU — evict the least frequently used. Suffers when an old page built up a big count long ago.",
    ]},
    {h: "Belady's anomaly"},
    {p: "Giving a process MORE frames should never produce MORE page faults. With FIFO it can. LRU and OPT are stack algorithms and are provably immune — that immunity is the exam answer."},
    {h: "Thrashing"},
    {p: "When processes have too few frames each, every one page-faults constantly and the system spends its time swapping instead of executing. CPU utilisation collapses while the disk saturates."},
    {p: "The trap: a naive scheduler sees low CPU utilisation and admits MORE processes, which makes it worse. The cure is fewer processes or more frames — the working-set model sizes the allocation to what each process is actually using."},
    {k: "Belady = Bad = FIFO. More frames making things worse only happens to the algorithm too dumb to look at usage."},
  ],
},
{
  key: "os-sync", subject: "Operating Systems", topic: "Operating Systems",
  title: "Synchronisation and Semaphores", minutes: 6,
  why: "The mutex-initialised-to-1 question is nearly guaranteed, and the three critical-section requirements are a free mark.",
  blocks: [
    {h: "The race condition"},
    {p: "Two processes read a shared counter as 5, both add 1, both write 6. One increment vanished. The outcome depends on timing, which is why these bugs are so hard to reproduce."},
    {h: "The critical section"},
    {p: "The stretch of code touching shared data. A correct solution needs exactly three properties:"},
    {l: [
      "Mutual exclusion — at most one process inside at a time.",
      "Progress — if nobody is inside, the decision of who enters cannot be postponed indefinitely.",
      "Bounded waiting — a limit on how many others may enter before a waiting process gets its turn.",
    ]},
    {p: "'Equal CPU time' is not one of them — that is a scheduling goal, and it is the usual wrong option."},
    {h: "Semaphores"},
    {p: "An integer with two atomic operations: wait() decrements and blocks if the result is negative; signal() increments and wakes a waiter."},
    {l: [
      "Binary semaphore (mutex) — initialised to 1. One key, one door.",
      "Counting semaphore — initialised to n, for n interchangeable resources.",
      "Initialised to 0 — used for signalling, to make one process wait for another to finish something.",
    ]},
    {k: "Mutex = 1. n resources = n. Signalling = 0. The value you initialise to IS the number allowed in at once."},
  ],
},

/* ─────────────────────────────── DBMS ─────────────────────────────── */
{
  key: "db-model", subject: "DBMS", topic: "DBMS",
  title: "The Relational Model and Keys", minutes: 7,
  why: "Normalisation is unlearnable without keys, and half of all key questions are just the superkey/candidate distinction.",
  blocks: [
    {h: "The vocabulary"},
    {p: "A relation is a table. A tuple is a row. An attribute is a column. The degree is the number of columns; the cardinality is the number of rows."},
    {h: "Functional dependency"},
    {p: "X → Y means: if two rows agree on X, they must agree on Y. X determines Y. roll_number → student_name is a functional dependency; the reverse is not, because two students can share a name."},
    {p: "This is the single idea normalisation is built on. Everything after this is 'which dependencies are allowed'."},
    {h: "The key hierarchy"},
    {l: [
      "Superkey — any set of attributes that identifies a row uniquely. May carry extras.",
      "Candidate key — a superkey with nothing removable. Minimal.",
      "Primary key — the candidate key the designer chose. Unique AND not null.",
      "Foreign key — an attribute referencing a primary key in another table.",
    ]},
    {p: "{roll_number, name} is a superkey but not a candidate key — drop 'name' and it still identifies the row. {roll_number} is the candidate key."},
    {h: "Prime and non-prime"},
    {p: "An attribute is prime if it belongs to any candidate key, non-prime otherwise. 2NF and 3NF are both stated in terms of non-prime attributes, so this is not optional vocabulary."},
    {k: "Superkey = unique. Candidate = unique AND minimal. Primary = the candidate you elected. Foreign = points elsewhere."},
  ],
},
{
  key: "db-normal", subject: "DBMS", topic: "DBMS",
  title: "Normalisation, 1NF to BCNF", minutes: 8,
  why: "The most examined DBMS topic. Four rules in order, each fixing one specific anomaly.",
  blocks: [
    {h: "What it is for"},
    {p: "Redundant data causes three anomalies: update (change it in one row, miss another), insertion (cannot record a department until someone works in it), and deletion (removing the last employee loses the department). Normalisation removes the redundancy that causes them."},
    {h: "1NF — atomic values"},
    {p: "Every cell holds a single value. No lists, no repeating groups. A phone_numbers column containing '9876543210, 9123456789' breaks 1NF."},
    {h: "2NF — no partial dependency"},
    {p: "In 1NF, and no non-prime attribute depends on only PART of a composite key."},
    {c: "{student_id, course_id} → grade        ← whole key, fine\n student_id              → student_name  ← PART of the key: partial dependency\n\nSplit: Student(student_id, student_name)\n       Enrolment(student_id, course_id, grade)"},
    {p: "It follows that a relation whose key is a single attribute is automatically in 2NF — there is no 'part' of it."},
    {h: "3NF — no transitive dependency"},
    {p: "In 2NF, and no non-prime attribute depends on another non-prime attribute."},
    {c: "student_id → dept_id → dept_name\n\nstudent_id determines dept_name only THROUGH dept_id — a middleman.\nSplit: Student(student_id, dept_id)  Dept(dept_id, dept_name)"},
    {h: "BCNF — every determinant is a key"},
    {p: "Stricter than 3NF: for every non-trivial X → Y, X must be a superkey. 3NF tolerates one exception — it also permits Y to be a prime attribute — and that exception is the only gap between them."},
    {k: "1NF atomic · 2NF no PARTIAL · 3NF no TRANSITIVE · BCNF determinant IS a key. Chant it in order."},
  ],
},
{
  key: "db-sql", subject: "DBMS", topic: "DBMS",
  title: "SQL — joins, grouping, NULL", minutes: 7,
  why: "Three areas produce nearly every SQL question: which join, WHERE vs HAVING, and how NULL behaves.",
  blocks: [
    {h: "Execution order — not the written order"},
    {c: "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY"},
    {p: "This explains the two classic errors. WHERE runs before grouping, so it cannot see aggregates — COUNT(*) in a WHERE is invalid; it belongs in HAVING. And SELECT runs after GROUP BY, so a column alias cannot be used in WHERE."},
    {h: "The joins"},
    {l: [
      "INNER JOIN — only rows matching on both sides.",
      "LEFT OUTER JOIN — every left row survives; unmatched right columns become NULL.",
      "RIGHT OUTER JOIN — the mirror image.",
      "FULL OUTER JOIN — everything from both, NULLs where unmatched.",
      "CROSS JOIN — every combination, m × n rows. A forgotten join condition silently becomes this.",
    ]},
    {p: "A trap worth knowing: filtering a right-hand column in WHERE turns a LEFT JOIN back into an INNER JOIN, because NULL fails the comparison. Put that condition in ON instead."},
    {h: "NULL is not a value"},
    {p: "NULL means unknown. Any comparison with it yields UNKNOWN, not TRUE — so `x = NULL` matches nothing, not even null rows. Use IS NULL. Likewise COUNT(*) counts all rows while COUNT(column) skips nulls; the difference between them is the number of nulls."},
    {h: "DDL vs DML"},
    {p: "DDL defines structure — CREATE, ALTER, DROP, TRUNCATE — and is normally auto-committed, so it cannot be rolled back. DML manipulates data — SELECT, INSERT, UPDATE, DELETE — and can be."},
    {k: "DELETE is DML, takes WHERE, can roll back. TRUNCATE is DDL, all rows, faster, no WHERE. DROP removes the table itself."},
  ],
},
{
  key: "db-txn", subject: "DBMS", topic: "DBMS",
  title: "Transactions, ACID and Concurrency", minutes: 7,
  why: "ACID is four free marks, and 2PL guaranteeing serializability but not freedom from deadlock is the classic trap.",
  blocks: [
    {h: "ACID"},
    {l: [
      "Atomicity — all or nothing. A partially applied transfer is rolled back.",
      "Consistency — the database moves from one valid state to another; constraints hold before and after.",
      "Isolation — concurrent transactions produce a result equivalent to running them one after another.",
      "Durability — once committed, it survives a crash. Achieved by writing the log before the data.",
    ]},
    {p: "Do not confuse the A with Availability, which is from the CAP theorem and a different subject entirely."},
    {h: "What goes wrong without isolation"},
    {l: [
      "Dirty read — reading data another transaction wrote and then rolled back.",
      "Non-repeatable read — reading the same row twice and getting different values.",
      "Phantom read — re-running a query and finding new rows that match.",
      "Lost update — two transactions write, one overwrites the other.",
    ]},
    {h: "Serializability"},
    {p: "A schedule is correct if it is equivalent to SOME serial order of the same transactions. Conflict serializability is tested by drawing a precedence graph: a cycle means it is not serializable."},
    {h: "Two-phase locking"},
    {p: "Every transaction has a growing phase (acquire locks only) and a shrinking phase (release only). Once it releases anything it may acquire nothing more. That ordering guarantees conflict serializability."},
    {p: "But 2PL does NOT prevent deadlock — two transactions can each hold what the other needs. That is why databases run a deadlock detector and abort a victim."},
    {k: "2PL buys correctness, not liveness. It still deadlocks; that is why a wait-for graph exists."},
  ],
},,

/* ────────────────────────── COMPUTER NETWORKS ────────────────────────── */
{
  key: "cn-layers", subject: "Computer Networks", topic: "Computer Networks",
  title: "The OSI and TCP/IP layers", minutes: 6,
  why: "Half of all networking questions are really 'which layer does this?'. Fix the layers first and those become free.",
  blocks: [
    {h: "Why layers at all"},
    {p: "Each layer solves one problem and hands the result down. Because the interface between layers is fixed, you can swap Wi-Fi for Ethernet without rewriting the web browser."},
    {h: "The seven, bottom to top"},
    {c: "7 Application   what the user's program speaks — HTTP, FTP, SMTP, DNS\n6 Presentation  encoding, compression, ENCRYPTION\n5 Session       opening, maintaining and closing a conversation\n4 Transport     end-to-end delivery — TCP, UDP, PORT numbers\n3 Network       routing between networks — IP, ROUTERS\n2 Data Link     delivery on one link — MAC, SWITCHES, frames\n1 Physical      the actual bits on the wire — cables, HUBS"},
    {p: "Bottom-up mnemonic: Please Do Not Throw Sausage Pizza Away."},
    {h: "Devices map to layers"},
    {p: "Hub = layer 1, switch = layer 2, router = layer 3. The device number matches its layer number, which is the fastest way to answer that family of questions."},
    {h: "TCP/IP is the same thing, condensed"},
    {p: "Four layers: Application (OSI 5-7), Transport, Internet (OSI 3), Network Access (OSI 1-2). OSI is the teaching model; TCP/IP is what actually runs."},
    {h: "Addresses per layer"},
    {c: "layer 2  MAC address   48-bit, burned into the card, LOCAL only\nlayer 3  IP address    32-bit (v4), routable across networks\nlayer 4  port number   16-bit, identifies the application"},
    {k: "MAC is local, IP travels, ports pick the program. Encryption is layer 6."},
  ],
},
{
  key: "cn-tcp-udp", subject: "Computer Networks", topic: "Computer Networks",
  title: "TCP vs UDP", minutes: 6,
  why: "One comparison, asked endlessly, and it explains why video calls drop frames instead of freezing.",
  blocks: [
    {h: "TCP — connection-oriented and reliable"},
    {l: [
      "Three-way handshake before any data: SYN → SYN-ACK → ACK.",
      "Every byte is numbered, acknowledged, and retransmitted if lost.",
      "Delivered in order, with flow control and congestion control.",
      "Header is 20 bytes minimum. Teardown is a four-way FIN exchange.",
    ]},
    {h: "UDP — connectionless and unreliable"},
    {l: [
      "No handshake. First packet carries data.",
      "No ordering, no retransmission, no congestion control.",
      "Header is 8 bytes. Far lower latency and overhead.",
    ]},
    {h: "Which, and why"},
    {p: "Use TCP when a missing byte ruins the result: web pages, file transfer, email. Use UDP when a late packet is worthless anyway: live video, voice, gaming, and DNS — where a handshake would cost more than the query itself."},
    {p: "That is why a bad video call shows a glitch and carries on rather than pausing to re-fetch a frame nobody needs any more."},
    {k: "TCP = phone call: dial, talk, confirm. UDP = postcard: send and forget."},
  ],
},
{
  key: "cn-ip", subject: "Computer Networks", topic: "Computer Networks",
  title: "IP addressing and subnetting", minutes: 8,
  why: "Subnetting is the one networking numerical that appears almost every year, and it is a formula plus a subtraction.",
  blocks: [
    {h: "The address"},
    {p: "IPv4 is 32 bits, written as four bytes: 192.168.1.10. A prefix like /24 says the first 24 bits identify the network and the rest identify the host."},
    {h: "The only formula you need"},
    {c: "host bits    = 32 − prefix\ntotal addrs  = 2^(host bits)\nUSABLE hosts = 2^(host bits) − 2\n\n  minus 2: the all-zeros address names the NETWORK,\n           the all-ones address is BROADCAST."},
    {c: "/24 → 2^8  − 2 = 254\n/25 → 2^7  − 2 = 126\n/26 → 2^6  − 2 = 62\n/27 → 2^5  − 2 = 30\n/28 → 2^4  − 2 = 14\n/30 → 2^2  − 2 = 2    (point-to-point links)"},
    {h: "Classes and default masks"},
    {c: "Class A  1-126     /8   255.0.0.0\nClass B  128-191   /16  255.255.0.0\nClass C  192-223   /24  255.255.255.0"},
    {h: "Private ranges"},
    {p: "10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16 are never routed on the internet. Note the middle one: it covers 172.16 to 172.31 only — 172.15 and 172.32 are public, and that boundary is the usual trap."},
    {k: "Usable = 2^(32−prefix) − 2. Always minus two, always."},
  ],
},
{
  key: "cn-protocols", subject: "Computer Networks", topic: "Computer Networks",
  title: "Protocols and port numbers", minutes: 5,
  why: "Pure recall, so pure marks. Learn the table once and never think about it again.",
  blocks: [
    {h: "The table"},
    {c: "20/21  FTP     file transfer (20 data, 21 control)\n22     SSH     secure shell\n23     Telnet  unencrypted remote login\n25     SMTP    SENDING mail\n53     DNS     name → IP\n67/68  DHCP    hands out IP addresses\n80     HTTP\n110    POP3    retrieving mail (downloads, deletes)\n143    IMAP    retrieving mail (stays on server)\n443    HTTPS   HTTP over TLS"},
    {h: "The ones that get confused"},
    {l: [
      "DNS maps a NAME to an IP. ARP maps an IP to a MAC. RARP does the reverse of ARP.",
      "DHCP gives you an address in the first place — remember DORA: Discover, Offer, Request, Acknowledge.",
      "SMTP sends; POP3 and IMAP receive. IMAP leaves mail on the server, POP3 pulls it down.",
      "ICMP carries errors and diagnostics — ping and traceroute. It has no ports at all, which is why a firewall can block ping while the site still loads.",
    ]},
    {k: "SMTP = Sending Mail To People. Everything else is the table above."},
  ],
},
{
  key: "cn-flow", subject: "Computer Networks", topic: "Computer Networks",
  title: "Errors, flow control and capacity", minutes: 6,
  why: "The formula half of networking: Nyquist, Shannon, and the sliding-window numericals.",
  blocks: [
    {h: "Error detection"},
    {l: [
      "Parity — one bit; catches an odd number of flipped bits only.",
      "Checksum — sum the words; used by IP, TCP and UDP headers.",
      "CRC — polynomial division, used at layer 2. Much stronger; detects all burst errors shorter than the CRC.",
      "Hamming code — can CORRECT a single-bit error, not merely detect it.",
    ]},
    {h: "Flow control"},
    {p: "Stop-and-Wait sends one frame and waits for its acknowledgement — simple, and terrible on a long link, because the line sits idle during the round trip."},
    {p: "Sliding window sends N frames before waiting. Go-Back-N retransmits everything from the lost frame onward; Selective Repeat retransmits only the lost one, at the cost of buffering out-of-order frames."},
    {h: "Channel capacity"},
    {c: "Nyquist (noiseless):  C = 2 × B × log₂L\nShannon (noisy):      C = B × log₂(1 + S/N)"},
    {p: "Pick by the wording: if the question mentions noise or a signal-to-noise ratio, it is Shannon. If it says noiseless and gives signal levels, it is Nyquist."},
    {k: "NOiseless = Nyquist. Noise ratio in the formula = Shannon."},
  ],
},

/* ─────────────────────────────── COA ─────────────────────────────── */
{
  key: "coa-number", subject: "COA", topic: "COA",
  title: "Number systems and 2's complement", minutes: 7,
  why: "Conversions appear directly and underpin every other COA question. Cheap marks if the method is automatic.",
  blocks: [
    {h: "Decimal to binary"},
    {p: "Subtract the largest power of two that fits, and repeat. Know these cold: 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024."},
    {c: "45 = 32 + 8 + 4 + 1\n     32 16  8  4  2  1\n      1  0  1  1  0  1   →  101101"},
    {h: "Hex is just four bits at a time"},
    {c: "1 hex digit = 4 bits.  1 byte = 2 hex digits.  Max byte = FF = 255.\n\n  255 = 1111 1111 = FF\n  A=10  B=11  C=12  D=13  E=14  F=15"},
    {h: "2's complement — how negatives are stored"},
    {p: "Invert every bit, then add 1. The leftmost bit becomes the sign: 0 positive, 1 negative."},
    {c: "+5 (4-bit) = 0101\ninvert     = 1010\nadd 1      = 1011  =  −5\n\nrange for n bits:  −2^(n−1)  to  +2^(n−1) − 1\n4 bits: −8 to +7   8 bits: −128 to +127"},
    {p: "Faster method: copy bits from the right up to and including the first 1, then flip everything to the left of it."},
    {h: "Why 2's complement and not sign-magnitude"},
    {p: "There is exactly one representation of zero, and subtraction becomes addition — the same adder circuit does both. Sign-magnitude has +0 and −0 and needs separate hardware."},
    {k: "Invert and add one. n bits reach −2^(n−1) to +2^(n−1) − 1 — one more negative than positive."},
  ],
},
{
  key: "coa-memory", subject: "COA", topic: "COA",
  title: "Memory hierarchy and cache", minutes: 8,
  why: "Cache mapping and the average-access-time formula are the most examined part of COA.",
  blocks: [
    {h: "The hierarchy"},
    {c: "registers → L1 → L2 → L3 → RAM → SSD → disk\nfaster, smaller, dearer  ←→  slower, bigger, cheaper"},
    {p: "It works only because of locality of reference. Temporal: an address used now is likely used again soon. Spatial: addresses near it are likely next. A loop over an array gives you both."},
    {h: "Cache mapping"},
    {l: [
      "Direct mapped — block goes to exactly one line: (block number) mod (number of lines). Cheapest, fastest lookup; two hot blocks landing on the same line thrash each other.",
      "Fully associative — any block in any line. No conflict misses, but every line must be compared, so the hardware is expensive.",
      "Set associative — the middle ground. k-way means a set of k lines; the block may sit in any line of its set.",
    ]},
    {h: "Address breakdown"},
    {c: "direct mapped:      TAG | LINE  | OFFSET\nset associative:    TAG | SET   | OFFSET\nfully associative:  TAG |       | OFFSET\n\noffset bits = log2(block size)\nline/set bits = log2(number of lines or sets)"},
    {h: "Average access time"},
    {c: "AAT = hit time + miss rate × miss penalty"},
    {p: "Read the question's convention carefully: 'miss penalty' sometimes means the EXTRA time on a miss and sometimes the TOTAL. That single reading decides the answer."},
    {k: "Direct = one seat. Fully associative = sit anywhere. Set associative = a row, any seat in it."},
  ],
},
{
  key: "coa-pipeline", subject: "COA", topic: "COA",
  title: "Pipelining and hazards", minutes: 7,
  why: "Speedup formulas and hazard types — mechanical marks once the vocabulary is straight.",
  blocks: [
    {h: "The idea"},
    {p: "Split instruction execution into stages so several instructions occupy different stages at once. The classic five: IF (fetch), ID (decode), EX (execute), MEM (memory), WB (write back)."},
    {p: "One instruction takes no less time — latency is unchanged or slightly worse. What improves is THROUGHPUT: once the pipe is full, one instruction completes every cycle."},
    {h: "The formulas"},
    {c: "k stages, n instructions, 1 cycle per stage:\n  non-pipelined time = n × k\n  pipelined time     = k + (n − 1)\n  speedup            = (n × k) / (k + n − 1)  →  k as n grows"},
    {h: "The three hazards"},
    {l: [
      "Structural — two instructions need the same hardware at once. Fixed by duplicating the unit (separate instruction and data caches).",
      "Data — an instruction needs a result not yet written. RAW is the true dependency; fixed by forwarding, or by stalling when forwarding cannot help (a load followed immediately by a use).",
      "Control — a branch means the next address is unknown. Fixed by branch prediction, or by flushing wrongly fetched instructions.",
    ]},
    {p: "WAR and WAW are name dependencies, not true ones — register renaming removes them entirely. RAW is the only one that reflects real data flow."},
    {k: "Laundry: one load still takes an hour, but you finish one every 20 minutes. RAW = Real dependency."},
  ],
},
{
  key: "coa-addressing", subject: "COA", topic: "COA",
  title: "Instructions and addressing modes", minutes: 6,
  why: "Identify-the-mode questions are recall, and the CPU-time formula shows up in every performance numerical.",
  blocks: [
    {h: "The instruction cycle"},
    {p: "Fetch (using the Program Counter) → Decode → Execute, with a memory and write-back stage in the pipelined view. The PC holds the address of the NEXT instruction; the Instruction Register holds the one being decoded. Those two are routinely confused."},
    {h: "Addressing modes"},
    {c: "Immediate   operand is IN the instruction        MOV R1, #5\nRegister    operand is in a register             MOV R1, R2\nDirect      instruction holds the ADDRESS         MOV R1, [1000]\nIndirect    instruction holds the address OF an\n            address                               MOV R1, [[1000]]\nIndexed     base + index register                 MOV R1, [R2+R3]\nRelative    PC + offset — used by branches"},
    {p: "Immediate is fastest: no memory access at all. Indirect is slowest: two memory reads before you touch the data."},
    {h: "Performance"},
    {c: "CPU time = (instruction count × CPI) / clock rate\nMIPS     = clock rate / (CPI × 10^6)"},
    {p: "That formula is why a higher clock does not always mean a faster processor — a design with a worse CPI can lose despite more GHz."},
    {k: "IMMEDIATE = the value is immediately there. INDIRECT = an address pointing at an address."},
  ],
},

/* ────────────────────── THEORY OF COMPUTATION ────────────────────── */
{
  key: "toc-automata", subject: "Theory of Computation", topic: "Theory of Computation",
  title: "Finite automata and regular languages", minutes: 6,
  why: "TOC is small in the syllabus and highly predictable. This lesson covers most of what is asked.",
  blocks: [
    {h: "A finite automaton"},
    {p: "States, an alphabet, transitions, one start state and a set of accepting states. It has NO memory beyond which state it is in — that limitation defines everything it cannot do."},
    {h: "DFA vs NFA"},
    {p: "A DFA has exactly one transition per symbol per state. An NFA may have several, or none, or epsilon moves. Every NFA converts to an equivalent DFA by subset construction, so they accept exactly the same class: the regular languages."},
    {p: "The NFA may be exponentially smaller, but it is not more powerful. 'More convenient' and 'more powerful' are different claims, and the exam tests whether you know which."},
    {h: "What regular languages cannot do"},
    {p: "They cannot count without bound. {aⁿbⁿ} is not regular, because after the a's you must remember how many there were, and a finite automaton has only finitely many states."},
    {p: "The pumping lemma proves a language is NOT regular, by contradiction. It can never prove one IS regular — passing it means nothing."},
    {h: "Closure"},
    {p: "Regular languages are closed under union, intersection, complement, concatenation and Kleene star — unusually well behaved. Context-free languages are NOT closed under intersection or complement."},
    {k: "If you must count without limit, it is not regular. Counting needs a stack."},
  ],
},
{
  key: "toc-hierarchy", subject: "Theory of Computation", topic: "Theory of Computation",
  title: "The Chomsky hierarchy", minutes: 5,
  why: "One table that answers a whole family of questions about which machine handles which language.",
  blocks: [
    {h: "The table"},
    {c: "Type 0  Recursively enumerable  Turing machine            unrestricted\nType 1  Context-sensitive       Linear bounded automaton  αAβ → αγβ\nType 2  Context-free            Pushdown automaton        A → γ\nType 3  Regular                 Finite automaton          A → aB | a"},
    {p: "The numbering runs opposite to power: Type 0 is the most powerful, Type 3 the least. Each class strictly contains the ones below it."},
    {h: "Memory is what separates them"},
    {c: "finite automaton   no memory              regular\npushdown automaton a STACK                 context-free\nlinear bounded     a bounded TAPE          context-sensitive\nTuring machine     an unbounded TAPE       recursively enumerable"},
    {h: "Decidability"},
    {p: "The Halting Problem is undecidable: no algorithm can decide, for every program and input, whether it halts. Undecidable does not mean 'hard' — it means no algorithm exists at any cost. NP-complete problems are merely expensive, and are a different thing entirely."},
    {k: "Count DOWN in power as the type number goes UP. More memory freedom, more power."},
  ],
},
{
  key: "toc-cfg", subject: "Theory of Computation", topic: "Theory of Computation",
  title: "Grammars and ambiguity", minutes: 5,
  why: "Ambiguity and parse trees round out the TOC questions that the automata lesson does not cover.",
  blocks: [
    {h: "A grammar"},
    {p: "Four parts: non-terminals (variables), terminals (alphabet symbols), production rules, and a start symbol. Derivation replaces non-terminals using the rules until only terminals remain."},
    {h: "Ambiguity"},
    {p: "A grammar is ambiguous if some string has more than one parse tree — equivalently, more than one leftmost derivation. Then the grammar does not determine the meaning."},
    {c: "E → E + E | E * E | id        ambiguous:\n\n  id + id * id  parses as (id+id)*id  OR  id+(id*id)\n\nFixed by encoding precedence in the rules:\n  E → E + T | T      T → T * F | F      F → id"},
    {p: "Ambiguity is a property of the GRAMMAR, not the language. Some languages are inherently ambiguous — no unambiguous grammar exists for them — but most are fixable."},
    {h: "Not the same problem"},
    {p: "Left recursion (A → Aα) breaks a top-down parser and is removed by rewriting, but it does not make a grammar ambiguous. Examiners offer it as a wrong option."},
    {k: "Two different trees for the same sentence = ambiguous. Left recursion is a parsing problem, not an ambiguity."},
  ],
},

/* ───────────────────── PROGRAMMING & OOP ───────────────────── */
{
  key: "prog-c", subject: "Programming & OOP", topic: "Programming & OOP",
  title: "C fundamentals that get examined", minutes: 7,
  why: "Output-prediction questions repeat a small set of traps. Learn the traps, not the language.",
  blocks: [
    {h: "Everything is passed by value"},
    {p: "C always copies the argument, so a function cannot change the caller's variable. Passing a POINTER by value simulates call-by-reference: you copy the address, then modify through it."},
    {c: "void bad(int x)  { x = 10; }        // caller unchanged\nvoid good(int *x){ *x = 10; }       // caller changed"},
    {h: "Storage classes"},
    {l: [
      "auto — the default for locals; created and destroyed with the block.",
      "static (local) — initialised once, keeps its value between calls, but stays visible only inside the function. Lifetime and scope are different things.",
      "static (global) — restricts a global to its own file.",
      "extern — declares something defined elsewhere.",
    ]},
    {h: "Pointer arithmetic counts elements"},
    {p: "For int *p on a 4-byte-int machine, p + 1 advances 4 bytes, not 1. That is exactly why a[i] and *(a + i) mean the same thing."},
    {h: "Sizes and the guarantees"},
    {p: "sizeof(char) is exactly 1 by definition — a 'byte' in C means whatever a char occupies. int, long and pointer sizes are machine dependent."},
    {h: "Undefined behaviour"},
    {p: "Modifying a variable twice in one expression — i++ + ++i — is undefined: different compilers legitimately print different values. Questions asking you to 'compute' these are testing whether you recognise them, not whether you can evaluate them."},
    {k: "Two modifications of one variable in one expression = undefined. Don't compute it, name it."},
  ],
},
{
  key: "prog-oop", subject: "Programming & OOP", topic: "Programming & OOP",
  title: "The four pillars of OOP", minutes: 6,
  why: "Definition questions, and the overloading-vs-overriding distinction that is asked every single time.",
  blocks: [
    {h: "A-PIE"},
    {l: [
      "Abstraction — expose what something does, hide how. A car's pedal, not its engine.",
      "Polymorphism — one interface, many forms.",
      "Inheritance — a derived class reuses and extends a base class.",
      "Encapsulation — data and the methods that use it bundled together, internals private.",
    ]},
    {h: "Encapsulation vs abstraction"},
    {p: "Encapsulation is the mechanism: private fields, public methods. Abstraction is the intent: showing only what matters. They are routinely offered as each other's definition."},
    {h: "The distinction that decides the mark"},
    {c: "OVERLOADING   same name, DIFFERENT signature, same class\n              resolved at COMPILE time (static polymorphism)\n\nOVERRIDING    same name, SAME signature, derived class\n              resolved at RUN time (dynamic polymorphism)"},
    {p: "Mnemonic: overLOADing is resolved early — the compiler loads it. OverRIDing is resolved late — the object decides at runtime."},
    {h: "Access modifiers"},
    {p: "private = this class only. protected = this class and its children. public = everyone. Default (package-private in Java) = same package."},
    {h: "Constructors"},
    {p: "Same name as the class, no return type at all — not even void — and run automatically on creation. A destructor tears down."},
    {k: "A-PIE. OverLOADing = compile time. OverRIDing = runtime."},
  ],
},
{
  key: "prog-recursion", subject: "Programming & OOP", topic: "Programming & OOP",
  title: "Recursion and tracing", minutes: 6,
  why: "Trace-the-output questions are guaranteed marks if you can do them on paper without panicking.",
  blocks: [
    {h: "Two obligations"},
    {p: "Every recursive function needs a base case that stops it, and every recursive call must move strictly toward that base case. Miss either and the call stack overflows."},
    {h: "How to trace one"},
    {p: "Write the calls downward as they are made, then evaluate upward as they return. The stack is literally what the machine does — mirroring it on paper is the whole method."},
    {c: "fact(4)\n  4 * fact(3)\n      3 * fact(2)\n          2 * fact(1)\n              1          ← base case\n          2 * 1 = 2\n      3 * 2 = 6\n  4 * 6 = 24"},
    {h: "Where the work happens matters"},
    {c: "void a(int n){ if(n>0){ printf(\"%d\",n); a(n-1); } }   // 3 2 1\nvoid b(int n){ if(n>0){ b(n-1); printf(\"%d\",n); } }   // 1 2 3"},
    {p: "Printing before the call gives descending order; printing after gives ascending, because the print waits for the whole descent to unwind. This exact pair is a favourite."},
    {h: "Cost"},
    {p: "Each pending call holds a stack frame, so recursion depth n uses O(n) memory even when the logic looks free. Naive fibonacci is O(2ⁿ) time because it recomputes the same values repeatedly."},
    {k: "Print BEFORE the call = descending. Print AFTER = ascending."},
  ],
},
{
  key: "prog-memory", subject: "Programming & OOP", topic: "Programming & OOP",
  title: "Memory: stack, heap and pointers", minutes: 6,
  why: "Explains dangling pointers, leaks and why a local array cannot be returned — all common questions.",
  blocks: [
    {h: "Where things live"},
    {c: "STACK   locals and parameters. Automatic, fast, freed on return.\n        Fixed, small. Overflow = infinite recursion.\nHEAP    malloc/new. Manual, you must free it. Large, slower.\nSTATIC  globals and statics. Lifetime of the whole program.\nCODE    the instructions themselves."},
    {h: "malloc"},
    {p: "Returns void*, which assigns to any object pointer type, and returns NULL when allocation fails — so the return value must always be checked. free() releases it; using the pointer afterwards is a dangling pointer, and freeing twice is undefined."},
    {h: "The classic bug"},
    {c: "char *bad(void){\n  char s[] = \"hello\";   // on the STACK\n  return s;             // freed the moment we return\n}"},
    {p: "The pointer survives; the memory does not. Returning heap memory is fine — the caller just has to free it."},
    {h: "Leak vs dangling"},
    {p: "A leak is memory you allocated and lost the pointer to — it can never be freed. A dangling pointer is memory you freed but are still pointing at. Opposite mistakes, both fatal."},
    {k: "Stack = automatic and short-lived. Heap = manual and lasts until you free it. Never return the address of a local."},
  ],
},

/* ────────────────────── SOFTWARE ENGINEERING ────────────────────── */
{
  key: "se-sdlc", subject: "Software Engineering", topic: "Software Engineering",
  title: "SDLC models", minutes: 5,
  why: "Recall marks. Each model has one defining property and that is what gets asked.",
  blocks: [
    {h: "The phases"},
    {p: "Requirements → Design → Implementation → Testing → Deployment → Maintenance. The models differ in how they move through them."},
    {h: "The models, one property each"},
    {l: [
      "Waterfall — strictly sequential, no overlap, going back is expensive. Suits stable, fully-understood requirements; fails when they change.",
      "V-model — the waterfall bent into a V, pairing each development phase with its matching test phase. Test planning starts at the beginning.",
      "Iterative / Incremental — build in slices, each adding function.",
      "Spiral — risk-driven. Every loop does plan, risk analysis, engineer, evaluate. For large, expensive, uncertain projects.",
      "Agile — short iterations, working software, welcomes changing requirements late.",
      "Prototype — build a throwaway to discover what the requirements actually are.",
    ]},
    {h: "SRS"},
    {p: "The Software Requirements Specification says WHAT the system must do — functional and non-functional. HOW belongs to the design document. If it names a technology, it has drifted into design."},
    {k: "Waterfall = water flows one way. Spiral = circling the risk. V = every spec has a matching test."},
  ],
},
{
  key: "se-testing", subject: "Software Engineering", topic: "Software Engineering",
  title: "Testing and design quality", minutes: 5,
  why: "Black box vs white box, the testing order, and cohesion/coupling — four reliable marks.",
  blocks: [
    {h: "Black box vs white box"},
    {p: "Black box works from the specification: given this input, expect this output, with no knowledge of the code. White box uses the code to exercise specific branches and paths. Grey box is a mix."},
    {h: "The levels, smallest first"},
    {c: "Unit         one function or class, by the developer\nIntegration  modules working together\nSystem       the whole product against requirements\nAcceptance   the customer decides if it is what they asked for"},
    {p: "Defects get exponentially more expensive the later they are found, which is the entire argument for testing early."},
    {h: "Other kinds worth naming"},
    {l: [
      "Regression — re-run existing tests to confirm a change broke nothing. Automated, because it runs constantly.",
      "Smoke — a quick check that the build is worth testing at all.",
      "Alpha — in-house. Beta — real users, real environment.",
      "Stress / load — behaviour beyond normal capacity.",
    ]},
    {h: "Design quality"},
    {p: "Aim for HIGH cohesion (a module does one thing well) and LOW coupling (modules depend on each other as little as possible), so one can change without a ripple through the rest."},
    {k: "Cohesion high, coupling low — opposite directions. Regression = checking nothing went backwards."},
  ],
},

/* ───────────────────── REASONING & ENGLISH ───────────────────── */
{
  key: "re-series", subject: "Reasoning & English", topic: "Reasoning & English",
  title: "Number series — a method, not a guess", minutes: 6,
  why: "40 marks of Part II, and series questions fall to a fixed procedure done in order.",
  blocks: [
    {h: "The procedure"},
    {p: "Work through these in order and stop at the first that fits. Do not stare at the numbers hoping — run the list."},
    {l: [
      "1. Write the DIFFERENCES underneath. Constant? Arithmetic series.",
      "2. Differences of the differences. Constant? Quadratic pattern.",
      "3. DIVIDE consecutive terms. Constant ratio? Geometric.",
      "4. Compare against squares and cubes: 1 4 9 16 25 / 1 8 27 64.",
      "5. Check for primes: 2 3 5 7 11 13 17 19 23.",
      "6. Try adding the previous two terms — Fibonacci.",
      "7. Look for two interleaved series in alternate positions.",
    ]},
    {h: "Worked examples"},
    {c: "2, 6, 12, 20, 30, ?\n  differences 4, 6, 8, 10 → next 12 → 42\n  (also n(n+1): 1×2, 2×3, 3×4 …)\n\n3, 8, 15, 24, 35, ?\n  n²−1: 4−1, 9−1, 16−1, 25−1, 36−1 → 49−1 = 48\n\n5, 10, 20, 40, ?\n  differences grow fast → try ratio → ×2 → 80"},
    {h: "What to memorise"},
    {p: "Squares to 20² and cubes to 10². Most series questions are a small perturbation of one of those, and recognising 361 as 19² instantly is the difference between five seconds and two minutes."},
    {k: "Differences first. If they grow fast, try dividing. Then squares, then primes, then Fibonacci."},
  ],
},
{
  key: "re-coding", subject: "Reasoning & English", topic: "Reasoning & English",
  title: "Coding-decoding and blood relations", minutes: 6,
  why: "Two mechanical topics that are pure marks once you have a method for each.",
  blocks: [
    {h: "Write the alphabet out first"},
    {p: "At the start of the paper, write A=1 to Z=26 in the margin. Every letter-shift question then takes seconds instead of counting on fingers. Learn the anchors: E=5, J=10, O=15, T=20, Y=25."},
    {h: "Coding-decoding method"},
    {p: "Derive the rule from the EXAMPLE given, verify it on a second letter, then apply. Never infer the rule from the options."},
    {c: "LOTUS → MPUVT     each letter +1\n  so ROSE → SPTF\n\nFRIEND → HTKGPF    each letter +2\n  so CANDLE → ECPFNG\n\nCAT → 3120         A=1..Z=26, concatenated\n  so DOG → 4,15,7 → 4157"},
    {h: "Blood relations method"},
    {p: "Draw generations as horizontal levels. 'Father/mother of' moves up a level, 'son/daughter of' moves down, 'brother/sister of' stays. Solve the innermost phrase first and work outward."},
    {c: "\"I have no brother or sister, but that man's\n father is my father's son.\"\n\n  my father's son, with no brothers = MYSELF\n  so that man's father = me\n  → the photo is my SON"},
    {h: "Direction sense"},
    {p: "Draw it. Opposite legs cancel; only the leftover legs count. If two perpendicular legs remain, the distance is Pythagoras. Remember a right turn while facing north points east."},
    {k: "Write the alphabet once. Draw the family as levels. Draw the directions as a map."},
  ],
},
{
  key: "re-grammar", subject: "Reasoning & English", topic: "Reasoning & English",
  title: "Error spotting — the rules that get tested", minutes: 6,
  why: "English errors come from a short list of rules. Learn the list and the questions become recognition.",
  blocks: [
    {h: "Subject-verb agreement"},
    {p: "The verb agrees with the SUBJECT, not the nearest noun. A phrase in between is deliberate distraction."},
    {c: "Each of the boys HAS finished.        (each = singular)\nOne of my friendS IS a doctor.       (plural noun, singular verb)\nThe list of items IS on the desk.    (subject = list, not items)"},
    {p: "Always singular: each, every, either, neither, none, everyone, somebody, nobody."},
    {h: "Third person singular"},
    {p: "He/she/it takes the S — either on the verb (he likes) or on the auxiliary (he does not like). 'He don't' is the classic planted error."},
    {h: "Articles"},
    {p: "'A' or 'an' depends on the SOUND, not the letter: a university (yoo), an hour (silent h), an MBA (em)."},
    {h: "Commonly confused pairs"},
    {c: "its (possessive)      / it's (it is)\nthan (comparison)     / then (time)\naffect (verb)         / effect (noun)\nprinciple (rule)      / principal (chief)\nstationary (still)    / stationery (paper)\nadvice (noun)         / advise (verb)"},
    {h: "Method"},
    {p: "Read the sentence aloud in your head, find the subject, find the verb, check they agree, then check tense consistency. Most errors surface in that one pass."},
    {k: "The verb agrees with the subject, never with the noun sitting next to it."},
  ],
},
{
  key: "re-vocab", subject: "Reasoning & English", topic: "Reasoning & English",
  title: "Vocabulary by word roots", minutes: 6,
  why: "You cannot memorise every word, but roots let you decode ones you have never met.",
  blocks: [
    {h: "The high-value roots"},
    {c: "BENE  good      benefit, benevolent, benign\nMAL   bad       malice, malevolent, malfunction\nMIS   wrong     misjudge, misanthrope\nPHIL  love      philosophy, bibliophile\nPHOBIA fear     claustrophobia\nCHRON time      chronological, anachronism\nBIO   life      biology, biography\nAUTO  self      autonomy, autobiography\nMONO  one       monologue, monopoly\nPOLY  many      polygon, polyglot\nANTE  before    antecedent          POST after\nPRE   before    precede             SUB under\nCIRCUM around   circumference       TRANS across"},
    {h: "How they answer questions"},
    {p: "Antonym of 'benevolent'? BENE is good, so the opposite carries MAL: malevolent. You need not have met the word before."},
    {h: "One-word substitution patterns"},
    {c: "-cide   killing        homicide, genocide\n-ology  study of       geology, cardiology\n-archy  rule           monarchy, anarchy\n-graphy writing        biography, calligraphy\n-phile  lover of       bibliophile"},
    {h: "The lookalike trap"},
    {p: "Options are chosen to resemble the right answer. Illiterate is a person; illegible is handwriting. Judicial concerns courts; judicious means showing good judgement. Read the ENDING — it usually says whether the word describes a person or a thing."},
    {k: "BENE good, MAL bad. Decode the root before guessing the word."},
  ],
},

/* ─────────────────────── GENERAL AWARENESS ─────────────────────── */
{
  key: "ga-hal", subject: "General Awareness", topic: "General Awareness",
  title: "HAL, defence and space — the static core", minutes: 5,
  why: "For a HAL paper this is the most likely GK, and unlike news it does not go stale.",
  blocks: [
    {h: "HAL itself"},
    {l: [
      "Founded 1940 in Bangalore as Hindustan Aircraft Limited, by Walchand Hirachand.",
      "Became Hindustan Aeronautics Limited in 1964, after merging with Aeronautics India Limited.",
      "Headquarters: Bengaluru. Under the Ministry of DEFENCE — not Civil Aviation.",
      "Divisions across Nashik, Koraput, Hyderabad, Lucknow, Kanpur and elsewhere.",
    ]},
    {h: "What HAL builds"},
    {c: "Tejas    Light Combat Aircraft (LCA)\nDhruv    Advanced Light Helicopter — indigenous design\nRudra    the weaponised Dhruv\nPrachand Light Combat Helicopter (LCH)\nHTT-40   basic trainer aircraft\nChetak / Cheetah — older licence-built designs"},
    {h: "Who does what"},
    {p: "DRDO researches and develops (Agni, Prithvi, Akash, the Arjun tank). HAL and BEL manufacture. Same ministry, different roles — and a favourite way to write a wrong option."},
    {h: "Space"},
    {p: "ISRO headquarters is Bengaluru. Launches happen at Sriharikota (SDSC-SHAR). VSSC at Thiruvananthapuram builds launch vehicles; SAC at Ahmedabad does satellite applications."},
    {k: "HAL and ISRO HQ are both Bengaluru. HAL flies, DRDO researches, BEL does electronics."},
  ],
},
{
  key: "ga-polity", subject: "General Awareness", topic: "General Awareness",
  title: "Constitution essentials", minutes: 5,
  why: "The most predictable static GK after the organisation itself — a handful of articles and parts.",
  blocks: [
    {h: "The Preamble"},
    {p: "Declares India a Sovereign, Socialist, Secular, Democratic Republic. 'Socialist' and 'Secular' were inserted by the 42nd Amendment in 1976 — the original read 'Sovereign Democratic Republic'."},
    {h: "The parts that matter"},
    {c: "Part III   Fundamental Rights        Articles 12-35\nPart IV    Directive Principles      Articles 36-51\nPart IVA   Fundamental Duties        Article 51A (42nd Amendment)"},
    {h: "Articles worth knowing by number"},
    {c: "14  Equality before law\n19  Freedom of speech and expression (six freedoms)\n21  Right to life and personal liberty\n21A Right to Education (86th Amendment)\n32  Right to Constitutional Remedies — move the Supreme Court\n226 High Court writ powers — wider than 32\n356 President's Rule"},
    {p: "Ambedkar called Article 32 'the heart and soul of the Constitution', because a right you cannot enforce is not a right."},
    {h: "The distinction that is always asked"},
    {p: "Fundamental Rights are justiciable — enforceable in court. Directive Principles are not; they are guidance to the State. Fundamental Duties are also non-justiciable."},
    {k: "Rights Part III, Directives Part IV, Duties Part IVA. Article 32 is the Supreme Court's door, 226 the High Court's."},
  ],
},
];
