/* ============================================================================
   CURRICULUM — teaches from zero, in dependency order.
   ----------------------------------------------------------------------------
   Each lesson is: read it, then prove it. A topic does not unlock the next one
   until you pass its check, so you cannot arrive at page-replacement algorithms
   without knowing what a page is.

   Order is deliberate. Big-O comes first because every later complexity claim
   is meaningless without it. Processes come before scheduling. Keys come before
   normalisation.

   Coverage: Data Structures, Operating Systems and DBMS — the three P1
   subjects, which carry the bulk of the 100 technical marks. The remaining
   subjects are practised from the question bank and get lessons as the mentor
   run adds them.

   Block types:
     h  heading          p  paragraph
     l  bullet list      c  code / worked example
     k  key point (the thing to remember)
   ========================================================================== */

const CURRICULUM = [

/* ─────────────────────────── DATA STRUCTURES ─────────────────────────── */
{
  key: "ds-bigo", subject: "Data Structures", topic: "Data Structures",
  title: "Reading Big-O", minutes: 7,
  video: {url:"https://www.youtube.com/watch?v=P5338HzZX7E",
          title:"Big O Notation | Asymptotic Notation | GATECSE | DAA", channel:"THE GATEHUB"},
  why: "Every later claim — 'a BST search is O(log n)' — is noise until you can read this notation. Start here.",
  blocks: [
    {h: "What it actually measures"},
    {p: "Big-O describes how the work grows as the input grows. It is not a stopwatch. O(n) does not mean 'n seconds' — it means doubling the input roughly doubles the work."},
    {p: "Constants and smaller terms are dropped, because they stop mattering as n gets large. 3n² + 500n + 9000 is O(n²): at n = 1,000,000 the n² term dwarfs everything else."},
    {h: "The ladder — memorise this once"},
    {c: "O(1) < O(log n) < O(√n) < O(n) < O(n log n) < O(n²) < O(2ⁿ) < O(n!)"},
    {l: [
      "O(1) — constant. Array index, hash lookup. Input size is irrelevant.",
      "O(log n) — halving each step. Binary search, balanced tree search.",
      "O(n) — touch everything once. A single loop over the data.",
      "O(n log n) — the best a comparison sort can do. Merge sort, heap sort.",
      "O(n²) — nested loop over the same data. Bubble, selection, insertion sort.",
    ]},
    {h: "How to spot it in code"},
    {p: "Count the nesting over the input. One loop over n items is O(n). A loop inside a loop, both over n, is O(n²). A loop that halves the range each pass is O(log n)."},
    {c: "for (i = 0; i < n; i++)          // O(n)\n  for (j = 0; j < n; j++)        // O(n) inside O(n)\n    sum += a[i] * a[j];          // → O(n²)\n\nwhile (n > 1) n = n / 2;         // O(log n) — halving"},
    {h: "Worst, average, best"},
    {p: "Exams almost always mean WORST case unless they say otherwise. QuickSort is O(n log n) on average but O(n²) at worst — and the worst case is the answer they want."},
    {k: "Halving → log. One pass → n. Nested passes → n². Anything that both splits and passes → n log n."},
  ],
},
{
  key: "ds-array-list", subject: "Data Structures", topic: "Data Structures",
  title: "Arrays and Linked Lists", minutes: 7,
  why: "The first real trade-off in the subject: instant access versus cheap insertion. Nearly every structure after this is built on one of them.",
  blocks: [
    {h: "Array — contiguous memory"},
    {p: "All elements sit next to each other, so the address of element i is base + i × size. One arithmetic step, no walking. That is why array access is O(1)."},
    {p: "The cost is insertion. To insert at the front, every other element must shift right — O(n). And the size is fixed at allocation."},
    {h: "Linked list — nodes and pointers"},
    {p: "Each node holds a value and the address of the next node. Nodes can be anywhere in memory, so growing costs nothing and inserting at the head is two pointer writes — O(1)."},
    {p: "The cost is access. There is no arithmetic shortcut to the 5th node; you must start at the head and follow 5 pointers — O(n)."},
    {h: "The trade-off in one table"},
    {c: "                 Array      Linked list\naccess i-th      O(1)       O(n)\ninsert at head   O(n)       O(1)\ninsert at tail   O(1)*      O(n) without a tail pointer\nsearch           O(n)       O(n)\nmemory           compact    extra pointer per node"},
    {p: "* amortised, if there is spare capacity."},
    {h: "Singly vs doubly"},
    {p: "A singly linked node knows only its successor. To delete a node you need its predecessor, so you walk from the head — O(n). A doubly linked node knows both neighbours, so deletion given a pointer is O(1)."},
    {k: "Array = address arithmetic = instant read, expensive insert. Linked list = pointer chasing = cheap insert, slow read."},
  ],
},
{
  key: "ds-stack-queue", subject: "Data Structures", topic: "Data Structures",
  title: "Stacks and Queues", minutes: 6,
  why: "Two structures with one rule each, and both turn up constantly — recursion, BFS, DFS, expression evaluation.",
  blocks: [
    {h: "Stack — LIFO"},
    {p: "Last in, first out. Push adds to the top, pop removes from the top. Both O(1). Think of a stack of plates: you can only take the one you put down last."},
    {l: [
      "Function calls — each call pushes an activation record, returns pop it. That is why recursion 'uses a stack'.",
      "Undo — the last action is the first undone.",
      "Postfix evaluation — push operands, and on an operator pop the last two.",
      "DFS — go as deep as possible, back up when stuck.",
    ]},
    {h: "Queue — FIFO"},
    {p: "First in, first out. Enqueue at the rear, dequeue from the front. Like a ticket counter: whoever arrived first is served first."},
    {l: [
      "BFS — explore all neighbours at one distance before going deeper.",
      "Scheduling — processes waiting for the CPU in arrival order.",
      "Buffers — printer jobs, keyboard input.",
    ]},
    {h: "The circular queue"},
    {p: "In a plain array queue, repeated dequeues leave dead space at the front that can never be reused, even when the queue is empty. Wrapping the rear pointer round to index 0 reclaims it."},
    {k: "BFS = Breadth = Queue. DFS = Depth = Stack. B-Q, D-S."},
  ],
},
{
  key: "ds-trees", subject: "Data Structures", topic: "Data Structures",
  title: "Trees and Binary Search Trees", minutes: 8,
  why: "The BST is where O(log n) first appears in a data structure, and traversal order is asked in almost every paper.",
  blocks: [
    {h: "Vocabulary first"},
    {l: [
      "Root — the single top node. Leaf — a node with no children.",
      "Height — the longest path from root to a leaf, counted in edges.",
      "A tree with n nodes has exactly n − 1 edges: every node but the root has one parent.",
      "Binary tree — each node has at most two children.",
    ]},
    {h: "The BST rule"},
    {p: "For every node: everything in the left subtree is smaller, everything in the right subtree is larger. That single rule is what makes search fast."},
    {p: "Searching, you compare once and discard an entire subtree. On a balanced tree of n nodes the height is log₂n, so search is O(log n)."},
    {h: "The catch"},
    {p: "Insert 1, 2, 3, 4, 5 into an empty BST in that order and every node becomes a right child. The tree is a linked list with extra steps, and search degrades to O(n). This is why AVL and red-black trees exist — they rebalance on insert."},
    {h: "Traversals"},
    {c: "Inorder    Left, Node, Right   → sorted order for a BST\nPreorder   Node, Left, Right   → copying / serialising a tree\nPostorder  Left, Right, Node   → deleting / freeing a tree\nLevel      row by row          → uses a QUEUE, not recursion"},
    {p: "The prefix tells you where the root is visited: PRE = first, IN = middle, POST = last."},
    {k: "IN-order gives INcreasing order. Postorder frees a tree safely — children die before their parent."},
  ],
},
{
  key: "ds-heap", subject: "Data Structures", topic: "Data Structures",
  title: "Heaps and Priority Queues", minutes: 6,
  why: "A heap looks like a tree and lives in an array. It is the answer to 'give me the largest thing, repeatedly'.",
  blocks: [
    {h: "The heap property"},
    {p: "In a max-heap every parent is ≥ its children. Apply that all the way up and the maximum must be at the root. A min-heap is the same rule inverted."},
    {p: "Note what it does NOT say: siblings are unordered, and a heap is not sorted. Only the root is guaranteed."},
    {h: "It is stored in an array"},
    {p: "A heap is a complete binary tree — every level full except possibly the last, filled left to right — so it maps onto an array with no gaps and no pointers."},
    {c: "for node at index i (0-based):\n  left child  = 2i + 1\n  right child = 2i + 2\n  parent      = (i − 1) / 2"},
    {h: "Costs"},
    {l: [
      "Find max — O(1). It is at index 0.",
      "Insert — put it at the end, then bubble up while it beats its parent. Bounded by the height: O(log n).",
      "Delete max — move the last element to the root, sift it down. O(log n).",
      "BUILD a heap from an unsorted array — O(n), not O(n log n). Most nodes are near the bottom and barely move.",
    ]},
    {k: "Build a heap = O(n). Heap SORT = O(n log n) — n deletions at log n each. Exams bank on you conflating the two."},
  ],
},
{
  key: "ds-graphs", subject: "Data Structures", topic: "Data Structures",
  title: "Graphs, BFS and DFS", minutes: 7,
  why: "Trees are a special case of graphs. Once you can traverse a graph, shortest paths and connectivity follow.",
  blocks: [
    {h: "Representation"},
    {p: "Adjacency matrix — a V × V grid, with a cell for every possible pair whether or not the edge exists. O(V²) space, O(1) edge lookup."},
    {p: "Adjacency list — for each vertex, a list of its actual neighbours. O(V + E) space. For sparse graphs, which is most real graphs, this is far better."},
    {h: "BFS — breadth first"},
    {p: "Visit all neighbours at distance 1, then distance 2, and so on. Uses a QUEUE. Because it expands in rings, the first time it reaches a node it has found the shortest path in edges — which is why BFS gives shortest paths on unweighted graphs."},
    {h: "DFS — depth first"},
    {p: "Go as deep as possible down one path, then back up and try the next. Uses a STACK, usually the call stack via recursion. Used for cycle detection, topological sort and connected components."},
    {c: "Both visit every vertex and edge once:\n  adjacency list   → O(V + E)\n  adjacency matrix → O(V²)   (you must scan a whole row per vertex)"},
    {k: "BFS = rings = queue = shortest path. DFS = tunnel = stack = cycles and ordering."},
  ],
},
{
  key: "ds-sorting", subject: "Data Structures", topic: "Data Structures",
  title: "Sorting — the comparison table", minutes: 7,
  why: "Sorting questions are nearly free marks, because they are almost always 'which one has this property'.",
  blocks: [
    {h: "The table to know cold"},
    {c: "            best        average     worst       stable  in-place\nBubble      O(n)        O(n²)       O(n²)       yes     yes\nSelection   O(n²)       O(n²)       O(n²)       no      yes\nInsertion   O(n)        O(n²)       O(n²)       yes     yes\nMerge       O(n log n)  O(n log n)  O(n log n)  yes     NO\nQuick       O(n log n)  O(n log n)  O(n²)       no      yes\nHeap        O(n log n)  O(n log n)  O(n log n)  no      yes"},
    {h: "Why QuickSort's worst case is O(n²)"},
    {p: "It picks a pivot and partitions around it. If the pivot is always the smallest or largest element, one side holds n − 1 items and the other holds none — so it recurses n deep doing O(n) work each time. An already-sorted array with a first-element pivot triggers exactly this."},
    {h: "Why MergeSort never has a bad day"},
    {p: "It splits at the midpoint regardless of the data — log n levels — and merges each level in O(n). The input cannot influence the split. The price is O(n) extra memory, so it is not in-place."},
    {h: "Stability"},
    {p: "A stable sort keeps equal elements in their original relative order. It matters when you sort by one key after another — sort by name, then by department, and a stable sort leaves each department alphabetical."},
    {k: "Stable: Merge, Insertion, Bubble, Counting. Not stable: Quick, Heap, Selection."},
  ],
},

/* ────────────────────────── OPERATING SYSTEMS ────────────────────────── */
{
  key: "os-process", subject: "Operating Systems", topic: "Operating Systems",
  title: "Processes and the PCB", minutes: 6,
  why: "Everything else in OS — scheduling, deadlock, memory — is about managing these. Start with what one is.",
  blocks: [
    {h: "Program vs process"},
    {p: "A program is a file on disk — passive. A process is a program in execution — active, with its own memory, registers and program counter. Run the same program twice and you have two processes."},
    {h: "The Process Control Block"},
    {p: "The OS keeps one PCB per process, holding its id, state, program counter, registers, memory pointers and open files. A context switch is: save the running process's state into its PCB, load the next process's PCB. Memory is not copied — the page tables just switch."},
    {p: "A context switch does no user work. It is pure overhead, which is why an extremely small scheduling quantum makes a system slower, not more responsive."},
    {h: "The five states"},
    {c: "new → ready ⇄ running → terminated\n              ↓   ↑\n           waiting (blocked on I/O)"},
    {p: "Only one process per CPU core is running at any instant. Ready means 'able to run, waiting for the CPU'. Waiting means 'cannot run until I/O completes' — a waiting process is not competing for the CPU at all."},
    {h: "Process vs thread"},
    {p: "Threads within a process share memory and open files; each has its own stack and registers. That makes switching between threads cheaper than between processes, and it is also why threads need synchronisation and separate processes usually do not."},
    {k: "Zombie = finished but the parent has not read its exit status. Orphan = still running, parent died, adopted by init."},
  ],
},
{
  key: "os-sched", subject: "Operating Systems", topic: "Operating Systems",
  title: "CPU Scheduling", minutes: 8,
  video: {url:"https://www.youtube.com/watch?v=zFnrUVqtiOY",
          title:"L-2.1: Process Scheduling Algorithms (Preemption vs Non-Preemption)", channel:"Gate Smashers"},
  why: "The most reliably examined OS topic, and the numericals are mechanical once you can draw a Gantt chart.",
  blocks: [
    {h: "The three numbers"},
    {c: "Completion time (CT) — when the process finishes\nTurnaround (TAT)      = CT − arrival time\nWaiting time (WT)     = TAT − burst time"},
    {p: "Draw the Gantt chart first, read completion times off it, then apply those two subtractions. Almost every scheduling numerical is that and nothing more."},
    {h: "The algorithms"},
    {l: [
      "FCFS — first come, first served. Non-preemptive. Simple, and suffers the convoy effect: one long process at the head delays everyone behind it.",
      "SJF — shortest job first. Provably optimal for average waiting time, but needs burst lengths in advance, which you do not have. Starves long jobs.",
      "SRTF — preemptive SJF. A shorter arrival preempts the running process.",
      "Round Robin — each process gets one quantum, then goes to the back of the queue. Preemptive, fair, nobody starves.",
      "Priority — highest priority first. Without aging, low-priority processes can starve forever.",
    ]},
    {h: "Round Robin's quantum"},
    {p: "Too large and no process is ever preempted, so it degenerates into FCFS. Too small and the system spends its time context switching instead of executing. The quantum should comfortably exceed a context switch but stay under a typical burst."},
    {h: "Starvation and its cure"},
    {p: "Starvation is indefinite postponement. Aging fixes it: raise a process's priority the longer it has waited, so anything waiting long enough eventually runs. FCFS and Round Robin cannot starve anyone by construction."},
    {k: "Optimal average waiting time = SJF. Convoy effect = FCFS. Starvation = priority without aging. Huge quantum = FCFS again."},
  ],
},
{
  key: "os-deadlock", subject: "Operating Systems", topic: "Operating Systems",
  title: "Deadlock", minutes: 7,
  video: {url:"https://www.youtube.com/watch?v=A46BUTxcNfw",
          title:"Operating System Unit 3 One Shot — CPU Scheduling + Deadlock", channel:"Bitwise Learning"},
  why: "Four conditions, four strategies. Learn them as two lists and the questions answer themselves.",
  blocks: [
    {h: "The four necessary conditions"},
    {p: "All four must hold simultaneously. Break any one and deadlock is impossible."},
    {l: [
      "Mutual exclusion — a resource cannot be shared.",
      "Hold and wait — a process holds one resource while waiting for another.",
      "No preemption — a resource cannot be forcibly taken away.",
      "Circular wait — a cycle of processes each waiting on the next.",
    ]},
    {p: "The trap: the third is NO preemption. 'Preemption' on its own is not a deadlock condition — allowing it breaks deadlock."},
    {h: "The four strategies"},
    {l: [
      "Prevention — structurally deny one of the four conditions. E.g. force resources to be requested in a fixed global order, which makes a cycle impossible.",
      "Avoidance — allow the conditions, but refuse any request that would leave an unsafe state. This is Banker's algorithm.",
      "Detection — let it happen, find cycles in the wait-for graph, then recover by killing or rolling back a process.",
      "Ignore it — the ostrich algorithm. What general-purpose systems mostly do, because deadlock is rare and the cures are expensive.",
    ]},
    {h: "Banker's algorithm"},
    {p: "Each process declares its maximum need up front. On a request, the OS pretends to grant it and checks whether a safe sequence still exists — an order in which every process can finish with the resources left. If yes, grant; if no, make it wait. A safe state is never a deadlock; an unsafe state is not necessarily a deadlock, only a risk."},
    {k: "A banker checks before lending — that is AVOIDANCE, not prevention."},
  ],
},
{
  key: "os-memory", subject: "Operating Systems", topic: "Operating Systems",
  title: "Memory, Paging and Fragmentation", minutes: 8,
  why: "Paging is the single most examined memory topic, and the internal/external fragmentation split is a guaranteed mark.",
  blocks: [
    {h: "The problem"},
    {p: "Several processes must share physical memory without reading each other's data, and a process may be larger than the RAM available."},
    {h: "Paging"},
    {p: "Split logical memory into fixed-size pages and physical memory into frames of the same size. A page table maps each page to a frame. Because the size is fixed, any page fits any frame — so there are no unusable gaps between allocations."},
    {p: "What you do get is waste inside the last page: a process rarely fills it exactly. That is INTERNAL fragmentation."},
    {h: "Segmentation"},
    {p: "Split memory by logical unit instead — code, stack, heap — each a different size. That matches how a program is actually structured, but variable sizes leave odd gaps between allocations. That is EXTERNAL fragmentation: plenty of total free memory, no single hole big enough."},
    {h: "The TLB"},
    {p: "Every memory access would need an extra read of the page table, doubling access time. The TLB is a small associative cache of recent page-table entries, so most translations take no extra memory access at all."},
    {c: "effective access time = h × (TLB + mem) + (1 − h) × (TLB + mem + mem)\n  where h is the TLB hit ratio"},
    {h: "Virtual memory"},
    {p: "Only the pages in active use need to be resident. The rest live on disk and are fetched on demand. A page fault is not an error — it is the normal mechanism: the MMU traps, the OS loads the page, and the instruction restarts."},
    {k: "Fixed size → INternal waste (inside the last page). Variable size → EXternal gaps (between segments)."},
  ],
},
{
  key: "os-pagerepl", subject: "Operating Systems", topic: "Operating Systems",
  title: "Page Replacement and Thrashing", minutes: 6,
  why: "Belady's anomaly is asked almost every year, and the numericals are pure bookkeeping.",
  blocks: [
    {h: "The question"},
    {p: "Memory is full and a new page is needed. Which resident page gets evicted? Count the page faults over a reference string and you have the whole topic."},
    {h: "The algorithms"},
    {l: [
      "FIFO — evict the oldest resident page. Ignores whether it is still being used.",
      "LRU — evict the least recently used. A good approximation of the future, expensive to track exactly.",
      "Optimal (OPT/MIN) — evict the page needed furthest in the future. Unimplementable, since it requires knowing the future; used as a benchmark.",
      "LFU — evict the least frequently used. Suffers when an old page built up a big count long ago.",
    ]},
    {h: "Belady's anomaly"},
    {p: "Giving a process MORE frames should never produce MORE page faults. With FIFO it can. LRU and OPT are stack algorithms and are provably immune — that immunity is the exam answer."},
    {h: "Thrashing"},
    {p: "When processes have too few frames each, every one page-faults constantly and the system spends its time swapping instead of executing. CPU utilisation collapses while the disk saturates."},
    {p: "The trap: a naive scheduler sees low CPU utilisation and admits MORE processes, which makes it worse. The cure is fewer processes or more frames — the working-set model sizes the allocation to what each process is actually using."},
    {k: "Belady = Bad = FIFO. More frames making things worse only happens to the algorithm too dumb to look at usage."},
  ],
},
{
  key: "os-sync", subject: "Operating Systems", topic: "Operating Systems",
  title: "Synchronisation and Semaphores", minutes: 6,
  why: "The mutex-initialised-to-1 question is nearly guaranteed, and the three critical-section requirements are a free mark.",
  blocks: [
    {h: "The race condition"},
    {p: "Two processes read a shared counter as 5, both add 1, both write 6. One increment vanished. The outcome depends on timing, which is why these bugs are so hard to reproduce."},
    {h: "The critical section"},
    {p: "The stretch of code touching shared data. A correct solution needs exactly three properties:"},
    {l: [
      "Mutual exclusion — at most one process inside at a time.",
      "Progress — if nobody is inside, the decision of who enters cannot be postponed indefinitely.",
      "Bounded waiting — a limit on how many others may enter before a waiting process gets its turn.",
    ]},
    {p: "'Equal CPU time' is not one of them — that is a scheduling goal, and it is the usual wrong option."},
    {h: "Semaphores"},
    {p: "An integer with two atomic operations: wait() decrements and blocks if the result is negative; signal() increments and wakes a waiter."},
    {l: [
      "Binary semaphore (mutex) — initialised to 1. One key, one door.",
      "Counting semaphore — initialised to n, for n interchangeable resources.",
      "Initialised to 0 — used for signalling, to make one process wait for another to finish something.",
    ]},
    {k: "Mutex = 1. n resources = n. Signalling = 0. The value you initialise to IS the number allowed in at once."},
  ],
},

/* ─────────────────────────────── DBMS ─────────────────────────────── */
{
  key: "db-model", subject: "DBMS", topic: "DBMS",
  title: "The Relational Model and Keys", minutes: 7,
  why: "Normalisation is unlearnable without keys, and half of all key questions are just the superkey/candidate distinction.",
  blocks: [
    {h: "The vocabulary"},
    {p: "A relation is a table. A tuple is a row. An attribute is a column. The degree is the number of columns; the cardinality is the number of rows."},
    {h: "Functional dependency"},
    {p: "X → Y means: if two rows agree on X, they must agree on Y. X determines Y. roll_number → student_name is a functional dependency; the reverse is not, because two students can share a name."},
    {p: "This is the single idea normalisation is built on. Everything after this is 'which dependencies are allowed'."},
    {h: "The key hierarchy"},
    {l: [
      "Superkey — any set of attributes that identifies a row uniquely. May carry extras.",
      "Candidate key — a superkey with nothing removable. Minimal.",
      "Primary key — the candidate key the designer chose. Unique AND not null.",
      "Foreign key — an attribute referencing a primary key in another table.",
    ]},
    {p: "{roll_number, name} is a superkey but not a candidate key — drop 'name' and it still identifies the row. {roll_number} is the candidate key."},
    {h: "Prime and non-prime"},
    {p: "An attribute is prime if it belongs to any candidate key, non-prime otherwise. 2NF and 3NF are both stated in terms of non-prime attributes, so this is not optional vocabulary."},
    {k: "Superkey = unique. Candidate = unique AND minimal. Primary = the candidate you elected. Foreign = points elsewhere."},
  ],
},
{
  key: "db-normal", subject: "DBMS", topic: "DBMS",
  title: "Normalisation, 1NF to BCNF", minutes: 8,
  why: "The most examined DBMS topic. Four rules in order, each fixing one specific anomaly.",
  blocks: [
    {h: "What it is for"},
    {p: "Redundant data causes three anomalies: update (change it in one row, miss another), insertion (cannot record a department until someone works in it), and deletion (removing the last employee loses the department). Normalisation removes the redundancy that causes them."},
    {h: "1NF — atomic values"},
    {p: "Every cell holds a single value. No lists, no repeating groups. A phone_numbers column containing '9876543210, 9123456789' breaks 1NF."},
    {h: "2NF — no partial dependency"},
    {p: "In 1NF, and no non-prime attribute depends on only PART of a composite key."},
    {c: "{student_id, course_id} → grade        ← whole key, fine\n student_id              → student_name  ← PART of the key: partial dependency\n\nSplit: Student(student_id, student_name)\n       Enrolment(student_id, course_id, grade)"},
    {p: "It follows that a relation whose key is a single attribute is automatically in 2NF — there is no 'part' of it."},
    {h: "3NF — no transitive dependency"},
    {p: "In 2NF, and no non-prime attribute depends on another non-prime attribute."},
    {c: "student_id → dept_id → dept_name\n\nstudent_id determines dept_name only THROUGH dept_id — a middleman.\nSplit: Student(student_id, dept_id)  Dept(dept_id, dept_name)"},
    {h: "BCNF — every determinant is a key"},
    {p: "Stricter than 3NF: for every non-trivial X → Y, X must be a superkey. 3NF tolerates one exception — it also permits Y to be a prime attribute — and that exception is the only gap between them."},
    {k: "1NF atomic · 2NF no PARTIAL · 3NF no TRANSITIVE · BCNF determinant IS a key. Chant it in order."},
  ],
},
{
  key: "db-sql", subject: "DBMS", topic: "DBMS",
  title: "SQL — joins, grouping, NULL", minutes: 7,
  why: "Three areas produce nearly every SQL question: which join, WHERE vs HAVING, and how NULL behaves.",
  blocks: [
    {h: "Execution order — not the written order"},
    {c: "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY"},
    {p: "This explains the two classic errors. WHERE runs before grouping, so it cannot see aggregates — COUNT(*) in a WHERE is invalid; it belongs in HAVING. And SELECT runs after GROUP BY, so a column alias cannot be used in WHERE."},
    {h: "The joins"},
    {l: [
      "INNER JOIN — only rows matching on both sides.",
      "LEFT OUTER JOIN — every left row survives; unmatched right columns become NULL.",
      "RIGHT OUTER JOIN — the mirror image.",
      "FULL OUTER JOIN — everything from both, NULLs where unmatched.",
      "CROSS JOIN — every combination, m × n rows. A forgotten join condition silently becomes this.",
    ]},
    {p: "A trap worth knowing: filtering a right-hand column in WHERE turns a LEFT JOIN back into an INNER JOIN, because NULL fails the comparison. Put that condition in ON instead."},
    {h: "NULL is not a value"},
    {p: "NULL means unknown. Any comparison with it yields UNKNOWN, not TRUE — so `x = NULL` matches nothing, not even null rows. Use IS NULL. Likewise COUNT(*) counts all rows while COUNT(column) skips nulls; the difference between them is the number of nulls."},
    {h: "DDL vs DML"},
    {p: "DDL defines structure — CREATE, ALTER, DROP, TRUNCATE — and is normally auto-committed, so it cannot be rolled back. DML manipulates data — SELECT, INSERT, UPDATE, DELETE — and can be."},
    {k: "DELETE is DML, takes WHERE, can roll back. TRUNCATE is DDL, all rows, faster, no WHERE. DROP removes the table itself."},
  ],
},
{
  key: "db-txn", subject: "DBMS", topic: "DBMS",
  title: "Transactions, ACID and Concurrency", minutes: 7,
  why: "ACID is four free marks, and 2PL guaranteeing serializability but not freedom from deadlock is the classic trap.",
  blocks: [
    {h: "ACID"},
    {l: [
      "Atomicity — all or nothing. A partially applied transfer is rolled back.",
      "Consistency — the database moves from one valid state to another; constraints hold before and after.",
      "Isolation — concurrent transactions produce a result equivalent to running them one after another.",
      "Durability — once committed, it survives a crash. Achieved by writing the log before the data.",
    ]},
    {p: "Do not confuse the A with Availability, which is from the CAP theorem and a different subject entirely."},
    {h: "What goes wrong without isolation"},
    {l: [
      "Dirty read — reading data another transaction wrote and then rolled back.",
      "Non-repeatable read — reading the same row twice and getting different values.",
      "Phantom read — re-running a query and finding new rows that match.",
      "Lost update — two transactions write, one overwrites the other.",
    ]},
    {h: "Serializability"},
    {p: "A schedule is correct if it is equivalent to SOME serial order of the same transactions. Conflict serializability is tested by drawing a precedence graph: a cycle means it is not serializable."},
    {h: "Two-phase locking"},
    {p: "Every transaction has a growing phase (acquire locks only) and a shrinking phase (release only). Once it releases anything it may acquire nothing more. That ordering guarantees conflict serializability."},
    {p: "But 2PL does NOT prevent deadlock — two transactions can each hold what the other needs. That is why databases run a deadlock detector and abort a victim."},
    {k: "2PL buys correctness, not liveness. It still deadlocks; that is why a wait-for graph exists."},
  ],
},
];
