/**
 * POST /api/progress — records what you did, so it exists somewhere other than
 * one phone's localStorage.
 *
 * WHY THIS IS A SERVER FUNCTION AND NOT A DIRECT SUPABASE CALL
 *
 * The browser holds the anon key (it is printed in index.html — that is normal
 * and by design). Migration 0002 removed a policy that let anyone holding that
 * key insert unlimited rows into quiz_attempts. Letting the page write progress
 * directly would put that hole straight back.
 *
 * So the page calls here, and this runs with the service-role key, which never
 * leaves the server. Everything below is validation: this endpoint is public,
 * so it must assume the body is hostile and refuse anything that is not the
 * exact shape it expects.
 *
 * GET /api/progress?device_id=… returns that device's state, so a reinstall or
 * a second device can pick the history back up.
 */

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.SUPABASE_URL ?? "";
const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";

/** Topics the client bank actually has. An unknown topic is a bad request, not
 *  a new topic — otherwise anyone could fill the table with junk categories and
 *  the weak-area analysis would be meaningless. */
const TOPICS = new Set([
  "Data Structures", "Operating Systems", "DBMS", "Computer Networks", "COA",
  "Theory of Computation", "Programming & OOP", "Software Engineering",
  "Reasoning & English", "General Awareness",
  "Quantitative Aptitude",   // SSC CGL; added with the SSC syllabus
]);

const QUALIFICATIONS = new Set(["B.Tech CSE", "Intermediate", "Graduate"]);

/** device_id is generated by crypto.randomUUID() in the browser. */
const isDeviceId = (v: unknown): v is string =>
  typeof v === "string" && /^[0-9a-f-]{36}$/i.test(v);

/** qid is 'q' + base36 of a 32-bit hash — see qid() in learn.html. */
const isQid = (v: unknown): v is string =>
  typeof v === "string" && /^q[0-9a-z]{1,7}$/.test(v);

/** A skill key from prep/skills.js: lowercase, dash-separated.
 *
 *  Deliberately validated by SHAPE and not against a hard-coded list of known
 *  skills. TOPICS above is such a list, and it caused a real failure: adding
 *  Quantitative Aptitude to the client bank made this endpoint reject whole
 *  batches until it was updated here too. The taxonomy is meant to grow every
 *  time the mentor run finds a new basic worth naming, and a deploy of the app
 *  must not be able to make this endpoint start dropping data. The build
 *  already refuses a question naming a skill that does not exist
 *  (scripts/validate-prep.js), so the real guarantee lives there; the job here
 *  is only to keep a hostile body from writing junk. */
const isSkillKey = (v: unknown): v is string =>
  typeof v === "string" && /^[a-z][a-z0-9-]{2,48}$/.test(v);

/** A question tests one basic, occasionally two. The cap is what stops a
 *  single attempt from turning into an unbounded number of rows. */
const MAX_SKILLS_PER_ATTEMPT = 4;

const isUuid = (v: unknown): v is string =>
  typeof v === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);

/** One quiz submission at a time is ~10 answers. 200 leaves room for a long
 *  offline session flushing at once, while capping what one request can insert. */
const MAX_ATTEMPTS_PER_REQUEST = 200;

export default async function handler(req: any, res: any) {
  if (!SUPABASE_URL || !SERVICE_KEY) {
    console.error("[progress] Supabase env vars are not set");
    return res.status(500).json({ error: "Server is not configured." });
  }
  const db = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });

  // ── GET ?summary=1: aggregate weak areas, no credentials ───────────────
  // The scheduled mentor run has no Supabase key and no way to know a device
  // id, so it reads the aggregate over plain HTTP. What this returns is topic
  // names and accuracy percentages — no identifiers, no device ids, nothing
  // about who you are. That is a deliberate trade: it is the minimum needed for
  // the loop to work, and none of it is worth anything to anyone else.
  if (req.method === "GET" && String(req.query?.summary ?? "") === "1") {
    const { data, error } = await db.from("study_weak_areas")
      .select("topic, answered, correct, accuracy, verdict, last_practised");
    if (error) {
      console.error("[progress] summary failed", error);
      return res.status(500).json({ error: "Could not read progress." });
    }
    // Collapse devices together: one person, possibly two phones.
    const byTopic: Record<string, any> = {};
    for (const r of data ?? []) {
      const t = byTopic[r.topic] || (byTopic[r.topic] = { topic: r.topic, answered: 0, correct: 0 });
      t.answered += r.answered ?? 0;
      t.correct  += r.correct ?? 0;
    }
    const topics = Object.values(byTopic).map((t: any) => {
      const accuracy = t.answered ? Math.round(100 * t.correct / t.answered) : null;
      return {
        ...t, accuracy,
        verdict: t.answered < 4 ? "unassessed"
               : accuracy < 60 ? "weak"
               : accuracy < 80 ? "developing" : "strong",
      };
    }).sort((a: any, b: any) => (a.accuracy ?? 999) - (b.accuracy ?? 999));

    // The same picture one level down. A topic tells the mentor run WHERE
    // marks are being lost; a skill tells it WHY, which is the difference
    // between writing ten more Reasoning questions and writing the four that
    // drill subject-verb agreement. A missing table or a failed read here must
    // not take the topic summary down with it — the loop worked on topics
    // alone before this existed and must keep working if this half is broken.
    let skills: any[] = [];
    const skillRes = await db.from("study_weak_skills")
      .select("skill, topic, answered, correct, distinct_missed, accuracy, last_practised");
    if (skillRes.error) {
      console.error("[progress] skill summary failed", skillRes.error);
    } else {
      const bySkill: Record<string, any> = {};
      for (const r of skillRes.data ?? []) {
        const s = bySkill[r.skill] || (bySkill[r.skill] = {
          skill: r.skill, topic: r.topic, answered: 0, correct: 0, distinct_missed: 0,
        });
        s.answered += r.answered ?? 0;
        s.correct  += r.correct ?? 0;
        // Summed across devices, which double-counts only in the case of the
        // same question missed on two phones. One person, one history — the
        // approximation is not worth a join to remove.
        s.distinct_missed += r.distinct_missed ?? 0;
      }
      skills = Object.values(bySkill).map((s: any) => {
        const accuracy = s.answered ? Math.round(100 * s.correct / s.answered) : null;
        return {
          ...s, accuracy,
          // Two DIFFERENT questions lost to one basic is evidence at this
          // grain, so it does not wait for the four-answer floor that topics
          // use. Being answered right clears it again.
          verdict: (s.answered >= 4 && accuracy >= 80) ? "strong"
                 : s.distinct_missed >= 2 ? "weak"
                 : s.answered < 4 ? "unassessed"
                 : accuracy < 60 ? "weak" : "developing",
        };
      }).sort((a: any, b: any) =>
        (b.distinct_missed - a.distinct_missed) || ((a.accuracy ?? 999) - (b.accuracy ?? 999)));
    }

    return res.status(200).json({
      topics,
      // Weak basics first in the payload as well as on screen: this is the
      // list the mentor run should act on, and the topic list is the symptom.
      skills,
      weak_skills: skills.filter((s: any) => s.verdict === "weak").map((s: any) => s.skill),
      total_answered: topics.reduce((n: number, t: any) => n + t.answered, 0),
      // Reaching this line means the database was read successfully — the
      // handler returns 500 above if the credentials are missing. So an empty
      // result means nobody has practised, NOT a misconfiguration. Saying
      // otherwise would send the mentor run chasing a problem that is not there.
      note: topics.length === 0
        ? "No practice recorded yet. The database is reachable and writes are working — there is simply nothing answered so far."
        : undefined,
    });
  }

  // ── GET: hand a device its own state back ──────────────────────────────
  if (req.method === "GET") {
    const deviceId = req.query?.device_id;
    if (!isDeviceId(deviceId)) return res.status(400).json({ error: "Bad device_id." });

    const [attempts, lessons, apps, profile] = await Promise.all([
      db.from("study_attempts").select("qid, topic, correct, skipped, answered_at")
        .eq("device_id", deviceId).order("answered_at", { ascending: false }).limit(3000),
      db.from("lesson_progress").select("topic_key, lesson_read, mastered").eq("device_id", deviceId),
      db.from("job_applications").select("job_id, applied, applied_at").eq("device_id", deviceId),
      db.from("study_profile").select("qualification").eq("device_id", deviceId).maybeSingle(),
    ]);

    return res.status(200).json({
      attempts: attempts.data ?? [],
      lessons:  lessons.data ?? [],
      applications: apps.data ?? [],
      qualification: profile.data?.qualification ?? null,
    });
  }

  if (req.method !== "POST") {
    res.setHeader("Allow", "GET, POST");
    return res.status(405).json({ error: "Method not allowed." });
  }

  // Vercel parses JSON bodies; a string body means a bad content-type.
  const body = typeof req.body === "string" ? safeParse(req.body) : req.body;
  if (!body || typeof body !== "object") return res.status(400).json({ error: "Bad body." });

  const deviceId = body.device_id;
  if (!isDeviceId(deviceId)) return res.status(400).json({ error: "Bad device_id." });

  try {
    switch (body.action) {
      case "attempts": {
        const rows = Array.isArray(body.attempts) ? body.attempts : [];
        if (rows.length === 0) return res.status(400).json({ error: "No attempts." });
        if (rows.length > MAX_ATTEMPTS_PER_REQUEST) {
          return res.status(413).json({ error: "Too many attempts in one request." });
        }
        // Every row is validated. One bad row rejects the batch rather than
        // being silently dropped — a silently missing answer would quietly
        // skew the weak-area maths, which is the whole point of this table.
        // A malformed row is rejected, but an UNKNOWN TOPIC is not the client
        // misbehaving — it is this list being out of date with the question
        // bank, which is exactly what happened when Quantitative Aptitude was
        // added for SSC CGL. Rejecting the batch for that reason threw away
        // every other answer in it, so a single Quant question could destroy a
        // whole quiz's progress. Skip what we do not recognise, keep the rest,
        // and report it so the gap is visible.
        const clean = [];
        const skillRows = [];
        const skippedTopics: string[] = [];
        for (const r of rows) {
          if (!isQid(r?.qid) || typeof r?.correct !== "boolean" || typeof r?.skipped !== "boolean") {
            return res.status(400).json({ error: "Bad attempt row." });
          }
          if (!TOPICS.has(r.topic)) {
            if (skippedTopics.indexOf(r.topic) === -1) skippedTopics.push(String(r.topic).slice(0, 40));
            continue;
          }
          clean.push({
            device_id: deviceId, qid: r.qid, topic: r.topic,
            correct: r.correct, skipped: r.skipped,
          });
          // The basics this question tests. Absent on most rows, and absent
          // entirely on rows queued by an older build of the app — neither is
          // an error, so an unusable value is dropped rather than failing the
          // batch and losing the answer itself with it.
          if (Array.isArray(r.skills)) {
            for (const s of r.skills.slice(0, MAX_SKILLS_PER_ATTEMPT)) {
              if (!isSkillKey(s)) continue;
              skillRows.push({
                device_id: deviceId, qid: r.qid, skill: s, topic: r.topic,
                correct: r.correct, skipped: r.skipped,
              });
            }
          }
        }
        if (clean.length === 0) {
          return res.status(400).json({ error: "No recognised attempts.", unknown_topics: skippedTopics });
        }
        const { error } = await db.from("study_attempts").insert(clean);
        if (error) throw error;
        // Written second and never allowed to fail the request. The attempt is
        // the record that matters; the skill breakdown is a finer view of it.
        // If this table is missing or a write fails, the answer must still be
        // saved rather than being retried forever by the client's queue.
        let skillsRecorded = 0;
        if (skillRows.length) {
          const { error: skillError } = await db.from("study_skill_attempts").insert(skillRows);
          if (skillError) console.error("[progress] skill attempts not recorded", skillError);
          else skillsRecorded = skillRows.length;
        }
        if (skippedTopics.length) console.warn("[progress] unknown topics skipped:", skippedTopics);
        return res.status(200).json({
          ok: true, recorded: clean.length,
          skills_recorded: skillsRecorded,
          unknown_topics: skippedTopics.length ? skippedTopics : undefined,
        });
      }

      case "lesson": {
        const key = body.topic_key;
        if (typeof key !== "string" || key.length === 0 || key.length > 80) {
          return res.status(400).json({ error: "Bad topic_key." });
        }
        const mastered = body.mastered === true;
        const { error } = await db.from("lesson_progress").upsert({
          device_id: deviceId,
          topic_key: key,
          lesson_read: body.lesson_read === true,
          mastered,
          mastered_at: mastered ? new Date().toISOString() : null,
          updated_at: new Date().toISOString(),
        }, { onConflict: "device_id,topic_key" });
        if (error) throw error;
        return res.status(200).json({ ok: true });
      }

      case "applied": {
        if (!isUuid(body.job_id)) return res.status(400).json({ error: "Bad job_id." });
        if (body.applied === false) {
          const { error } = await db.from("job_applications")
            .delete().eq("device_id", deviceId).eq("job_id", body.job_id);
          if (error) throw error;
          return res.status(200).json({ ok: true, applied: false });
        }
        const { error } = await db.from("job_applications").upsert({
          device_id: deviceId, job_id: body.job_id,
          applied: true, applied_at: new Date().toISOString(),
        }, { onConflict: "device_id,job_id" });
        if (error) throw error;
        return res.status(200).json({ ok: true, applied: true });
      }

      case "profile": {
        const q = body.qualification;
        if (q !== null && !QUALIFICATIONS.has(q)) {
          return res.status(400).json({ error: "Bad qualification." });
        }
        const { error } = await db.from("study_profile").upsert({
          device_id: deviceId, qualification: q, updated_at: new Date().toISOString(),
        }, { onConflict: "device_id" });
        if (error) throw error;
        return res.status(200).json({ ok: true });
      }

      default:
        return res.status(400).json({ error: "Unknown action." });
    }
  } catch (e) {
    // Never return the raw Postgres message to a public endpoint.
    console.error("[progress]", e);
    return res.status(500).json({ error: "Could not save progress." });
  }
}

function safeParse(s: string) {
  try { return JSON.parse(s); } catch { return null; }
}
